//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camion
    {
        public Camion()
        {
            this.PackingList = new HashSet<PackingList>();
            this.FolioAvisoLlegada = new HashSet<FolioAvisoLlegada>();
            this.Plana = new HashSet<Plana>();
        }
    
        public int CamionID { get; set; }
        public int TransportistaID { get; set; }
        public int ChoferID { get; set; }
        public string Placas { get; set; }
        public string TarjetaCirulacion { get; set; }
        public string PolizaSeguro { get; set; }
        public string Estatus { get; set; }
        public int EntidadID { get; set; }
        public bool Activo { get; set; }
    
        public virtual Chofer Chofer { get; set; }
        public virtual Entidad Entidad { get; set; }
        public virtual ICollection<PackingList> PackingList { get; set; }
        public virtual Transportista Transportista { get; set; }
        public virtual ICollection<FolioAvisoLlegada> FolioAvisoLlegada { get; set; }
        public virtual ICollection<Plana> Plana { get; set; }
    }
}
