//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorteDetalle
    {
        public int CorteDetalleID { get; set; }
        public int CorteID { get; set; }
        public int OrdenTrabajoSpoolID { get; set; }
        public int MaterialSpoolID { get; set; }
        public Nullable<int> SalidaInventarioID { get; set; }
        public int Cantidad { get; set; }
        public Nullable<System.DateTime> FechaCorte { get; set; }
        public Nullable<int> MaquinaID { get; set; }
        public bool Cancelado { get; set; }
        public bool EsAjuste { get; set; }
        public int EntidadID { get; set; }
    
        public virtual Corte Corte { get; set; }
        public virtual Entidad Entidad { get; set; }
        public virtual Maquina Maquina { get; set; }
        public virtual MaterialSpool MaterialSpool { get; set; }
        public virtual NumeroUnicoMovimiento NumeroUnicoMovimiento { get; set; }
        public virtual OrdenTrabajoSpool OrdenTrabajoSpool { get; set; }
    }
}
