//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entidad
    {
        public Entidad()
        {
            this.Acero = new HashSet<Acero>();
            this.Camion = new HashSet<Camion>();
            this.Chofer = new HashSet<Chofer>();
            this.Cliente = new HashSet<Cliente>();
            this.Colada = new HashSet<Colada>();
            this.Color = new HashSet<Color>();
            this.Contacto = new HashSet<Contacto>();
            this.Corte = new HashSet<Corte>();
            this.CorteDetalle = new HashSet<CorteDetalle>();
            this.Diametro = new HashSet<Diametro>();
            this.EstatusOrden = new HashSet<EstatusOrden>();
            this.ExtensionDocumento = new HashSet<ExtensionDocumento>();
            this.Fabricante = new HashSet<Fabricante>();
            this.FamiliaAcero = new HashSet<FamiliaAcero>();
            this.FamiliaItemCode = new HashSet<FamiliaItemCode>();
            this.FolioAvisoLlegada = new HashSet<FolioAvisoLlegada>();
            this.FolioLlegada = new HashSet<FolioLlegada>();
            this.FolioPackingList = new HashSet<FolioPackingList>();
            this.Incidencia = new HashSet<Incidencia>();
            this.ItemCode = new HashSet<ItemCode>();
            this.Maquina = new HashSet<Maquina>();
            this.MaterialSpool = new HashSet<MaterialSpool>();
            this.MenuContextual = new HashSet<MenuContextual>();
            this.Notificacion = new HashSet<Notificacion>();
            this.NumeroUnico = new HashSet<NumeroUnico>();
            this.NumeroUnicoCorte = new HashSet<NumeroUnicoCorte>();
            this.NumeroUnicoInventario = new HashSet<NumeroUnicoInventario>();
            this.NumeroUnicoMovimiento = new HashSet<NumeroUnicoMovimiento>();
            this.NumeroUnicoSegmento = new HashSet<NumeroUnicoSegmento>();
            this.OrdenTrabajo = new HashSet<OrdenTrabajo>();
            this.OrdenTrabajoSpool = new HashSet<OrdenTrabajoSpool>();
            this.PackingList = new HashSet<PackingList>();
            this.Pagina = new HashSet<Pagina>();
            this.Patio = new HashSet<Patio>();
            this.Perfil = new HashSet<Perfil>();
            this.PermisoAduana = new HashSet<PermisoAduana>();
            this.PinturaNumeroUnico = new HashSet<PinturaNumeroUnico>();
            this.Plana = new HashSet<Plana>();
            this.Preferencia = new HashSet<Preferencia>();
            this.Propiedad = new HashSet<Propiedad>();
            this.Proveedor = new HashSet<Proveedor>();
            this.Proyecto = new HashSet<Proyecto>();
            this.Recepcion = new HashSet<Recepcion>();
            this.Rel_Documento_Entidad = new HashSet<Rel_Documento_Entidad>();
            this.FamiliaMaterial = new HashSet<FamiliaMaterial>();
            this.Rel_FolioAvisoLlegada_Proyecto = new HashSet<Rel_FolioAvisoLlegada_Proyecto>();
            this.Rel_Incidencia_Entidad = new HashSet<Rel_Incidencia_Entidad>();
            this.Rel_Perfil_Propiedad_Pagina = new HashSet<Rel_Perfil_Propiedad_Pagina>();
            this.Repositorio = new HashSet<Repositorio>();
            this.Rel_Usuario_Preferencia = new HashSet<Rel_Usuario_Preferencia>();
            this.Rel_Usuario_Proyecto = new HashSet<Rel_Usuario_Proyecto>();
            this.RequisicionNumeroUnico = new HashSet<RequisicionNumeroUnico>();
            this.RequisicionNumeroUnicoDetalle = new HashSet<RequisicionNumeroUnicoDetalle>();
            this.Sesion = new HashSet<Sesion>();
            this.Spool = new HashSet<Spool>();
            this.Taller = new HashSet<Taller>();
            this.TipoCorte = new HashSet<TipoCorte>();
            this.TipoDocumento = new HashSet<TipoDocumento>();
            this.TipoMaterial = new HashSet<TipoMaterial>();
            this.TipoMovimiento = new HashSet<TipoMovimiento>();
            this.TipoNotificacion = new HashSet<TipoNotificacion>();
            this.Transportista = new HashSet<Transportista>();
            this.UbicacionFisica = new HashSet<UbicacionFisica>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int EntidadID { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Acero> Acero { get; set; }
        public virtual ICollection<Camion> Camion { get; set; }
        public virtual ICollection<Chofer> Chofer { get; set; }
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Colada> Colada { get; set; }
        public virtual ICollection<Color> Color { get; set; }
        public virtual ICollection<Contacto> Contacto { get; set; }
        public virtual ICollection<Corte> Corte { get; set; }
        public virtual ICollection<CorteDetalle> CorteDetalle { get; set; }
        public virtual ICollection<Diametro> Diametro { get; set; }
        public virtual ICollection<EstatusOrden> EstatusOrden { get; set; }
        public virtual ICollection<ExtensionDocumento> ExtensionDocumento { get; set; }
        public virtual ICollection<Fabricante> Fabricante { get; set; }
        public virtual ICollection<FamiliaAcero> FamiliaAcero { get; set; }
        public virtual ICollection<FamiliaItemCode> FamiliaItemCode { get; set; }
        public virtual ICollection<FolioAvisoLlegada> FolioAvisoLlegada { get; set; }
        public virtual ICollection<FolioLlegada> FolioLlegada { get; set; }
        public virtual ICollection<FolioPackingList> FolioPackingList { get; set; }
        public virtual ICollection<Incidencia> Incidencia { get; set; }
        public virtual ICollection<ItemCode> ItemCode { get; set; }
        public virtual ICollection<Maquina> Maquina { get; set; }
        public virtual ICollection<MaterialSpool> MaterialSpool { get; set; }
        public virtual ICollection<MenuContextual> MenuContextual { get; set; }
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        public virtual ICollection<NumeroUnico> NumeroUnico { get; set; }
        public virtual ICollection<NumeroUnicoCorte> NumeroUnicoCorte { get; set; }
        public virtual ICollection<NumeroUnicoInventario> NumeroUnicoInventario { get; set; }
        public virtual ICollection<NumeroUnicoMovimiento> NumeroUnicoMovimiento { get; set; }
        public virtual ICollection<NumeroUnicoSegmento> NumeroUnicoSegmento { get; set; }
        public virtual ICollection<OrdenTrabajo> OrdenTrabajo { get; set; }
        public virtual ICollection<OrdenTrabajoSpool> OrdenTrabajoSpool { get; set; }
        public virtual ICollection<PackingList> PackingList { get; set; }
        public virtual ICollection<Pagina> Pagina { get; set; }
        public virtual ICollection<Patio> Patio { get; set; }
        public virtual ICollection<Perfil> Perfil { get; set; }
        public virtual ICollection<PermisoAduana> PermisoAduana { get; set; }
        public virtual ICollection<PinturaNumeroUnico> PinturaNumeroUnico { get; set; }
        public virtual ICollection<Plana> Plana { get; set; }
        public virtual ICollection<Preferencia> Preferencia { get; set; }
        public virtual ICollection<Propiedad> Propiedad { get; set; }
        public virtual ICollection<Proveedor> Proveedor { get; set; }
        public virtual ICollection<Proyecto> Proyecto { get; set; }
        public virtual ICollection<Recepcion> Recepcion { get; set; }
        public virtual ICollection<Rel_Documento_Entidad> Rel_Documento_Entidad { get; set; }
        public virtual ICollection<FamiliaMaterial> FamiliaMaterial { get; set; }
        public virtual ICollection<Rel_FolioAvisoLlegada_Proyecto> Rel_FolioAvisoLlegada_Proyecto { get; set; }
        public virtual ICollection<Rel_Incidencia_Entidad> Rel_Incidencia_Entidad { get; set; }
        public virtual ICollection<Rel_Perfil_Propiedad_Pagina> Rel_Perfil_Propiedad_Pagina { get; set; }
        public virtual ICollection<Repositorio> Repositorio { get; set; }
        public virtual ICollection<Rel_Usuario_Preferencia> Rel_Usuario_Preferencia { get; set; }
        public virtual ICollection<Rel_Usuario_Proyecto> Rel_Usuario_Proyecto { get; set; }
        public virtual ICollection<RequisicionNumeroUnico> RequisicionNumeroUnico { get; set; }
        public virtual ICollection<RequisicionNumeroUnicoDetalle> RequisicionNumeroUnicoDetalle { get; set; }
        public virtual ICollection<Sesion> Sesion { get; set; }
        public virtual ICollection<Spool> Spool { get; set; }
        public virtual ICollection<Taller> Taller { get; set; }
        public virtual ICollection<TipoCorte> TipoCorte { get; set; }
        public virtual ICollection<TipoDocumento> TipoDocumento { get; set; }
        public virtual ICollection<TipoMaterial> TipoMaterial { get; set; }
        public virtual ICollection<TipoMovimiento> TipoMovimiento { get; set; }
        public virtual ICollection<TipoNotificacion> TipoNotificacion { get; set; }
        public virtual ICollection<Transportista> Transportista { get; set; }
        public virtual ICollection<UbicacionFisica> UbicacionFisica { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
