//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entidad
    {
        public Entidad()
        {
            this.Bitacora = new HashSet<Bitacora>();
            this.Camion = new HashSet<Camion>();
            this.ExtensionDocumento = new HashSet<ExtensionDocumento>();
            this.FamiliaItemCode = new HashSet<FamiliaItemCode>();
            this.FolioAvisoLlegada = new HashSet<FolioAvisoLlegada>();
            this.FolioLlegada = new HashSet<FolioLlegada>();
            this.FolioPackingList = new HashSet<FolioPackingList>();
            this.Incidencia = new HashSet<Incidencia>();
            this.MenuContextual = new HashSet<MenuContextual>();
            this.Notificacion = new HashSet<Notificacion>();
            this.NumeroUnico = new HashSet<NumeroUnico>();
            this.NumeroUnicoInventario = new HashSet<NumeroUnicoInventario>();
            this.NumeroUnicoMovimiento = new HashSet<NumeroUnicoMovimiento>();
            this.NumeroUnicoSegmento = new HashSet<NumeroUnicoSegmento>();
            this.PackingList = new HashSet<PackingList>();
            this.Pagina = new HashSet<Pagina>();
            this.Perfil1 = new HashSet<Perfil>();
            this.PermisoAduana = new HashSet<PermisoAduana>();
            this.Plana = new HashSet<Plana>();
            this.Preferencia = new HashSet<Preferencia>();
            this.Propiedad = new HashSet<Propiedad>();
            this.Recepcion = new HashSet<Recepcion>();
            this.Rel_Documento_Entidad = new HashSet<Rel_Documento_Entidad>();
            this.Rel_FolioAvisoLlegada_Proyecto = new HashSet<Rel_FolioAvisoLlegada_Proyecto>();
            this.Rel_Incidencia_Entidad = new HashSet<Rel_Incidencia_Entidad>();
            this.Rel_Perfil_Propiedad_Pagina = new HashSet<Rel_Perfil_Propiedad_Pagina>();
            this.Repositorio = new HashSet<Repositorio>();
            this.Rel_Usuario_Preferencia = new HashSet<Rel_Usuario_Preferencia>();
            this.Rel_Usuario_Proyecto = new HashSet<Rel_Usuario_Proyecto>();
            this.RequisicionNumeroUnico = new HashSet<RequisicionNumeroUnico>();
            this.RequisicionNumeroUnicoDetalle = new HashSet<RequisicionNumeroUnicoDetalle>();
            this.Sesion = new HashSet<Sesion>();
            this.TipoActividad = new HashSet<TipoActividad>();
            this.TipoDocumento = new HashSet<TipoDocumento>();
            this.TipoMovimiento = new HashSet<TipoMovimiento>();
            this.TipoNotificacion = new HashSet<TipoNotificacion>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int EntidadID { get; set; }
        public int PerfilID { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Bitacora> Bitacora { get; set; }
        public virtual ICollection<Camion> Camion { get; set; }
        public virtual Perfil Perfil { get; set; }
        public virtual ICollection<ExtensionDocumento> ExtensionDocumento { get; set; }
        public virtual ICollection<FamiliaItemCode> FamiliaItemCode { get; set; }
        public virtual ICollection<FolioAvisoLlegada> FolioAvisoLlegada { get; set; }
        public virtual ICollection<FolioLlegada> FolioLlegada { get; set; }
        public virtual ICollection<FolioPackingList> FolioPackingList { get; set; }
        public virtual ICollection<Incidencia> Incidencia { get; set; }
        public virtual ICollection<MenuContextual> MenuContextual { get; set; }
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        public virtual ICollection<NumeroUnico> NumeroUnico { get; set; }
        public virtual ICollection<NumeroUnicoInventario> NumeroUnicoInventario { get; set; }
        public virtual ICollection<NumeroUnicoMovimiento> NumeroUnicoMovimiento { get; set; }
        public virtual ICollection<NumeroUnicoSegmento> NumeroUnicoSegmento { get; set; }
        public virtual ICollection<PackingList> PackingList { get; set; }
        public virtual ICollection<Pagina> Pagina { get; set; }
        public virtual ICollection<Perfil> Perfil1 { get; set; }
        public virtual ICollection<PermisoAduana> PermisoAduana { get; set; }
        public virtual ICollection<Plana> Plana { get; set; }
        public virtual ICollection<Preferencia> Preferencia { get; set; }
        public virtual ICollection<Propiedad> Propiedad { get; set; }
        public virtual ICollection<Recepcion> Recepcion { get; set; }
        public virtual ICollection<Rel_Documento_Entidad> Rel_Documento_Entidad { get; set; }
        public virtual ICollection<Rel_FolioAvisoLlegada_Proyecto> Rel_FolioAvisoLlegada_Proyecto { get; set; }
        public virtual ICollection<Rel_Incidencia_Entidad> Rel_Incidencia_Entidad { get; set; }
        public virtual ICollection<Rel_Perfil_Propiedad_Pagina> Rel_Perfil_Propiedad_Pagina { get; set; }
        public virtual ICollection<Repositorio> Repositorio { get; set; }
        public virtual ICollection<Rel_Usuario_Preferencia> Rel_Usuario_Preferencia { get; set; }
        public virtual ICollection<Rel_Usuario_Proyecto> Rel_Usuario_Proyecto { get; set; }
        public virtual ICollection<RequisicionNumeroUnico> RequisicionNumeroUnico { get; set; }
        public virtual ICollection<RequisicionNumeroUnicoDetalle> RequisicionNumeroUnicoDetalle { get; set; }
        public virtual ICollection<Sesion> Sesion { get; set; }
        public virtual ICollection<TipoActividad> TipoActividad { get; set; }
        public virtual ICollection<TipoDocumento> TipoDocumento { get; set; }
        public virtual ICollection<TipoMovimiento> TipoMovimiento { get; set; }
        public virtual ICollection<TipoNotificacion> TipoNotificacion { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
