//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamiliaAcero
    {
        public FamiliaAcero()
        {
            this.Acero = new HashSet<Acero>();
            this.ItemCode = new HashSet<ItemCode>();
            this.Spool = new HashSet<Spool>();
            this.Spool1 = new HashSet<Spool>();
        }
    
        public int FamiliaAceroID { get; set; }
        public int FamiliaMaterialID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool VerificadoPorCalidad { get; set; }
        public int EntidadID { get; set; }
    
        public virtual ICollection<Acero> Acero { get; set; }
        public virtual Entidad Entidad { get; set; }
        public virtual FamiliaMaterial FamiliaMaterial { get; set; }
        public virtual ICollection<ItemCode> ItemCode { get; set; }
        public virtual ICollection<Spool> Spool { get; set; }
        public virtual ICollection<Spool> Spool1 { get; set; }
    }
}
