//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolioAvisoLlegada
    {
        public FolioAvisoLlegada()
        {
            this.FolioLlegada = new HashSet<FolioLlegada>();
            this.PermisoAduana = new HashSet<PermisoAduana>();
        }
    
        public int FolioAvisoLlegadaID { get; set; }
        public Nullable<int> CamionID { get; set; }
        public Nullable<int> Consecutivo { get; set; }
        public Nullable<bool> EsVirtual { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> EntidadID { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Camion Camion { get; set; }
        public virtual Entidad Entidad { get; set; }
        public virtual ICollection<FolioLlegada> FolioLlegada { get; set; }
        public virtual ICollection<PermisoAduana> PermisoAduana { get; set; }
    }
}
