//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencia
    {
        public Incidencia()
        {
            this.Incidencia1 = new HashSet<Incidencia>();
        }
    
        public int IncidenciaID { get; set; }
        public Nullable<int> IncidenciaOriginalID { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> NoRFI { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioID { get; set; }
        public string Respuesta { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
        public Nullable<int> UsuarioIDRespuesta { get; set; }
        public int Version { get; set; }
        public string Estatus { get; set; }
        public int EntidadID { get; set; }
        public bool Activo { get; set; }
    
        public virtual Entidad Entidad { get; set; }
        public virtual ICollection<Incidencia> Incidencia1 { get; set; }
        public virtual Incidencia Incidencia2 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Rel_Incidencia_Entidad Rel_Incidencia_Entidad { get; set; }
    }
}
