//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingList
    {
        public PackingList()
        {
            this.FolioPackingList = new HashSet<FolioPackingList>();
        }
    
        public int PackingListID { get; set; }
        public int ProyectoID { get; set; }
        public int CamionID { get; set; }
        public int FolioLlegadaID { get; set; }
        public Nullable<int> Consecutivo { get; set; }
        public int EntidadID { get; set; }
        public bool Activo { get; set; }
    
        public virtual Camion Camion { get; set; }
        public virtual Entidad Entidad { get; set; }
        public virtual FolioLlegada FolioLlegada { get; set; }
        public virtual ICollection<FolioPackingList> FolioPackingList { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
