//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepcion
    {
        public Recepcion()
        {
            this.NumeroUnico = new HashSet<NumeroUnico>();
        }
    
        public int RecepcionID { get; set; }
        public int FolioPackingListID { get; set; }
        public int ItemCodeID { get; set; }
        public Nullable<int> FamiliaItemCodeID { get; set; }
        public Nullable<int> CedulaID { get; set; }
        public Nullable<int> TipoAceroID { get; set; }
        public Nullable<decimal> Diametro1 { get; set; }
        public Nullable<decimal> Diametro2 { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<bool> TieneNumerosUnicos { get; set; }
        public Nullable<System.DateTime> FechaGeneracionNumerosUnicos { get; set; }
        public int EntidadID { get; set; }
        public bool Activo { get; set; }
    
        public virtual Entidad Entidad { get; set; }
        public virtual FamiliaItemCode FamiliaItemCode { get; set; }
        public virtual FolioPackingList FolioPackingList { get; set; }
        public virtual ICollection<NumeroUnico> NumeroUnico { get; set; }
    }
}
