//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_PinturaSpool_Obrero
    {
        public int PinturaSpoolObreroId { get; set; }
        public Nullable<int> PinturaSpoolID { get; set; }
        public Nullable<int> ObreroID { get; set; }
        public Nullable<int> PasoID { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_Obrero Sam3_Obrero { get; set; }
        public virtual Sam3_PinturaSpool Sam3_PinturaSpool { get; set; }
    }
}
