//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_NumeroUnico
    {
        public int NumeroUnicoID { get; set; }
        public int ProyectoID { get; set; }
        public Nullable<int> ItemCodeID { get; set; }
        public Nullable<int> ColadaID { get; set; }
        public Nullable<int> ProveedorID { get; set; }
        public Nullable<int> FabricanteID { get; set; }
        public Nullable<int> TipoCorte1ID { get; set; }
        public Nullable<int> TipoCorte2ID { get; set; }
        public string Estatus { get; set; }
        public string Factura { get; set; }
        public string PartidaFactura { get; set; }
        public string OrdenDeCompra { get; set; }
        public string PartidaOrdenDeCompra { get; set; }
        public Nullable<decimal> Diametro1 { get; set; }
        public Nullable<decimal> Diametro2 { get; set; }
        public string Cedula { get; set; }
        public string NumeroUnicoCliente { get; set; }
        public Nullable<bool> MarcadoAsme { get; set; }
        public Nullable<bool> MarcadoGolpe { get; set; }
        public Nullable<bool> MarcadoPintura { get; set; }
        public string PruebasHidrostaticas { get; set; }
        public Nullable<bool> TieneDano { get; set; }
        public string Rack { get; set; }
        public string Observaciones { get; set; }
        public string CampoLibreRecepcion1 { get; set; }
        public string CampoLibreRecepcion2 { get; set; }
        public string CampoLibreRecepcion3 { get; set; }
        public string CampoLibreRecepcion4 { get; set; }
        public string CampoLibreRecepcion5 { get; set; }
        public string CampoLibre1 { get; set; }
        public string CampoLibre2 { get; set; }
        public string CampoLibre3 { get; set; }
        public string CampoLibre4 { get; set; }
        public string CampoLibre5 { get; set; }
        public Nullable<bool> EsVirtual { get; set; }
        public Nullable<int> RecepcionID { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Prefijo { get; set; }
        public int Consecutivo { get; set; }
    }
}
