//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_ProyectoConsecutivo
    {
        public int ProyectoID { get; set; }
        public int ConsecutivoFolioAvisollegada { get; set; }
        public int ConsecutivoFolioEntradaMateiral { get; set; }
        public int ConsecutivoFolioDescargaMaterial { get; set; }
        public int ConsecutivoPaseSalida { get; set; }
        public int ConsecutivoPermisoAduana { get; set; }
        public int ConsucutivoFolioPackingList { get; set; }
        public int ConsecutivoODT { get; set; }
        public int ConsecutivoNumerounico { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public int ConsecutivoOrdeRecepcion { get; set; }
        public int ConsecutivoOrdenAlmacenaje { get; set; }
    
        public virtual Sam3_Proyecto Sam3_Proyecto { get; set; }
    }
}
