//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_JuntaSoldadura
    {
        public int JuntaSoldaduraID { get; set; }
        public int DetalleArmadoID { get; set; }
        public Nullable<int> ProcesoSoldaduraRaizID { get; set; }
        public Nullable<int> ProcesoSoldaduraRellenoID { get; set; }
        public int TallerID { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> FechaSoldadura { get; set; }
        public Nullable<System.DateTime> FechaReporte { get; set; }
        public int UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public Nullable<int> ColadaID { get; set; }
    
        public virtual Sam3_DetalleArmado Sam3_DetalleArmado { get; set; }
        public virtual Sam3_ProcesoSoldadura Sam3_ProcesoSoldadura { get; set; }
        public virtual Sam3_ProcesoSoldadura Sam3_ProcesoSoldadura1 { get; set; }
    }
}
