//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Corte
    {
        public Sam3_Corte()
        {
            this.Sam3_CorteDetalle = new HashSet<Sam3_CorteDetalle>();
        }
    
        public int CorteID { get; set; }
        public int ProyectoID { get; set; }
        public Nullable<int> NumeroUnicoCorteID { get; set; }
        public Nullable<int> Sobrante { get; set; }
        public Nullable<int> Merma { get; set; }
        public Nullable<int> MermaMovimientoID { get; set; }
        public Nullable<int> PreparacionCorteMovimientoID { get; set; }
        public bool Cancelado { get; set; }
        public string Rack { get; set; }
        public Nullable<int> CortadorID { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_NumeroUnicoMovimiento Sam3_NumeroUnicoMovimiento { get; set; }
        public virtual Sam3_NumeroUnicoMovimiento Sam3_NumeroUnicoMovimiento1 { get; set; }
        public virtual Sam3_Proyecto Sam3_Proyecto { get; set; }
        public virtual ICollection<Sam3_CorteDetalle> Sam3_CorteDetalle { get; set; }
    }
}
