//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_FamiliaAcero
    {
        public Sam3_FamiliaAcero()
        {
            this.Sam3_Acero = new HashSet<Sam3_Acero>();
            this.Sam3_ItemCode = new HashSet<Sam3_ItemCode>();
            this.Sam3_Spool = new HashSet<Sam3_Spool>();
            this.Sam3_Spool1 = new HashSet<Sam3_Spool>();
        }
    
        public int FamiliaAceroID { get; set; }
        public int FamiliaMaterialID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool VerificadoPorCalidad { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Sam3_Acero> Sam3_Acero { get; set; }
        public virtual Sam3_FamiliaMaterial Sam3_FamiliaMaterial { get; set; }
        public virtual ICollection<Sam3_ItemCode> Sam3_ItemCode { get; set; }
        public virtual ICollection<Sam3_Spool> Sam3_Spool { get; set; }
        public virtual ICollection<Sam3_Spool> Sam3_Spool1 { get; set; }
    }
}
