//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_ElementoPorClasificacionPND_Borrar
    {
        public int ElementoPorClasificacionPNDID { get; set; }
        public int OrdenTrabajoID { get; set; }
        public Nullable<int> JuntaSpoolID { get; set; }
        public Nullable<int> SpoolID { get; set; }
        public Nullable<int> ClasificacionPNDID { get; set; }
    }
}
