//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Cedula
    {
        public Sam3_Cedula()
        {
            this.Sam3_ItemCodeSteelgo = new HashSet<Sam3_ItemCodeSteelgo>();
        }
    
        public int CedulaID { get; set; }
        public string CedulaA { get; set; }
        public string CedulaB { get; set; }
        public string CedulaC { get; set; }
        public decimal CedulaIn { get; set; }
        public decimal CedulaMM { get; set; }
        public decimal Espesor { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> DiametroID { get; set; }
    
        public virtual ICollection<Sam3_ItemCodeSteelgo> Sam3_ItemCodeSteelgo { get; set; }
        public virtual Sam3_Diametro Sam3_Diametro { get; set; }
    }
}
