//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Rel_FolioCuantificacion_ItemCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sam3_Rel_FolioCuantificacion_ItemCode()
        {
            this.Sam3_Rel_NumeroUnico_RelFC_RelB = new HashSet<Sam3_Rel_NumeroUnico_RelFC_RelB>();
        }
    
        public int Rel_FolioCuantificacion_ItemCode_ID { get; set; }
        public int FolioCuantificacionID { get; set; }
        public Nullable<int> ItemCodeID { get; set; }
        public bool TieneNumerosUnicos { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Rel_ItemCode_Diametro_ID { get; set; }
        public Nullable<int> MM { get; set; }
        public int ColadaID { get; set; }
        public Nullable<decimal> DimensionPromedio { get; set; }
    
        public virtual Sam3_FolioCuantificacion Sam3_FolioCuantificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sam3_Rel_NumeroUnico_RelFC_RelB> Sam3_Rel_NumeroUnico_RelFC_RelB { get; set; }
        public virtual Sam3_Rel_ItemCode_Diametro Sam3_Rel_ItemCode_Diametro { get; set; }
    }
}
