//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_TipoVehiculo
    {
        public Sam3_TipoVehiculo()
        {
            this.Sam3_Vehiculo = new HashSet<Sam3_Vehiculo>();
        }
    
        public int TipoVehiculoID { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
    
        public virtual ICollection<Sam3_Vehiculo> Sam3_Vehiculo { get; set; }
    }
}
