//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_InspeccionDimensional
    {
        public int InspeccionDimensionalID { get; set; }
        public Nullable<int> OrdenTrabajoSpoolID { get; set; }
        public int ResultadoID { get; set; }
        public Nullable<int> DefectoID { get; set; }
        public int ObreroID { get; set; }
        public System.DateTime FechaInspeccion { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    }
}
