//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_FolioPackingList
    {
        public Sam3_FolioPackingList()
        {
            this.Sam3_Recepcion = new HashSet<Sam3_Recepcion>();
        }
    
        public int FolioPackingListID { get; set; }
        public Nullable<int> PackingListID { get; set; }
        public Nullable<int> FolioLlegadaID { get; set; }
        public string Folio { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public System.DateTime FechaCapturaCompleta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_FolioLlegada Sam3_FolioLlegada { get; set; }
        public virtual Sam3_PackingList Sam3_PackingList { get; set; }
        public virtual ICollection<Sam3_Recepcion> Sam3_Recepcion { get; set; }
    }
}
