//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_TipoNotificacion
    {
        public Sam3_TipoNotificacion()
        {
            this.Sam3_Notificacion = new HashSet<Sam3_Notificacion>();
        }
    
        public int TipoNotificacionID { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Sam3_Notificacion> Sam3_Notificacion { get; set; }
    }
}
