//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_NumeroUnicoCorte
    {
        public int NumeroUnicoCorteID { get; set; }
        public int NumeroUnicoID { get; set; }
        public int ProyectoID { get; set; }
        public int SalidaMovimientoID { get; set; }
        public int OrdenTrabajoID { get; set; }
        public Nullable<int> UbicacionFisicaID { get; set; }
        public string Segmento { get; set; }
        public int Longitud { get; set; }
        public System.DateTime FechaTraspaso { get; set; }
        public bool TieneCorte { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_NumeroUnico Sam3_NumeroUnico { get; set; }
        public virtual Sam3_NumeroUnicoMovimiento Sam3_NumeroUnicoMovimiento { get; set; }
        public virtual Sam3_OrdenTrabajo Sam3_OrdenTrabajo { get; set; }
        public virtual Sam3_Proyecto Sam3_Proyecto { get; set; }
        public virtual Sam3_UbicacionFisica Sam3_UbicacionFisica { get; set; }
    }
}
