//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Rel_Clasificacion_TipoPrueba
    {
        public int ClasificacionTipoPruebaID { get; set; }
        public int ClasificacionPNDID { get; set; }
        public int TipoPruebaID { get; set; }
        public Nullable<int> Activo { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<bool> RequiereEquipo { get; set; }
        public Nullable<bool> RequiereEntregaDocumento { get; set; }
        public Nullable<bool> RequiereSoldadura { get; set; }
        public Nullable<int> TipoPruebaPorSpool { get; set; }
    }
}
