//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_V_InspeccionVisual
    {
        public int DetalleArmadoID { get; set; }
        public int OrdenTrabajoSpoolID { get; set; }
        public int JuntaTrabajoAnteriorID { get; set; }
        public int TipoJuntaID { get; set; }
        public string EtiquetaJunta { get; set; }
        public int EtiquetaMaterial1 { get; set; }
        public int EtiquetaMaterial2 { get; set; }
        public Nullable<int> JuntaArmadoID { get; set; }
        public Nullable<int> NumeroUnico1ID { get; set; }
        public Nullable<int> NumeroUnico2ID { get; set; }
        public Nullable<System.DateTime> FechaArmado { get; set; }
        public Nullable<int> JuntaSoldaduraID { get; set; }
        public Nullable<System.DateTime> FechaSoldadura { get; set; }
        public Nullable<int> InspeccionVisualID { get; set; }
        public Nullable<int> DefectoID { get; set; }
        public Nullable<int> ObreroID { get; set; }
        public Nullable<System.DateTime> FechaInspeccion { get; set; }
        public Nullable<int> ResultadoID { get; set; }
        public Nullable<int> TallerID { get; set; }
    }
}
