//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_JuntaSoldadura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sam3_JuntaSoldadura()
        {
            this.Sam3_JuntaSoldaduraSoldado = new HashSet<Sam3_JuntaSoldaduraSoldado>();
            this.Sam3_JuntaSoldaduraTrabajoAdicional = new HashSet<Sam3_JuntaSoldaduraTrabajoAdicional>();
        }
    
        public int JuntaSoldaduraID { get; set; }
        public int JuntaTrabajoID { get; set; }
        public int ProcesoSoldaduraRaizID { get; set; }
        public int ProcesoSoldaduraRellenoID { get; set; }
        public int TallerID { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> FechaSoldadura { get; set; }
        public Nullable<System.DateTime> FechaReporte { get; set; }
        public int UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual Sam3_JuntaTrabajo Sam3_JuntaTrabajo { get; set; }
        public virtual Sam3_ProcesoSoldadura Sam3_ProcesoSoldadura { get; set; }
        public virtual Sam3_ProcesoSoldadura Sam3_ProcesoSoldadura1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sam3_JuntaSoldaduraSoldado> Sam3_JuntaSoldaduraSoldado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sam3_JuntaSoldaduraTrabajoAdicional> Sam3_JuntaSoldaduraTrabajoAdicional { get; set; }
    }
}
