//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_SpoolHoldhistorial
    {
        public int SpoolHoldHistorialID { get; set; }
        public int SpoolID { get; set; }
        public string TipoHold { get; set; }
        public System.DateTime FechaHold { get; set; }
        public string Observaciones { get; set; }
        public int Activo { get; set; }
        public int UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
