//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_JuntaArmado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sam3_JuntaArmado()
        {
            this.sam3_JuntaArmadoTrabajoAdicional = new HashSet<sam3_JuntaArmadoTrabajoAdicional>();
        }
    
        public int JuntaArmadoID { get; set; }
        public Nullable<int> JuntaWorkStatusID { get; set; }
        public Nullable<int> NumeroUnico1ID { get; set; }
        public Nullable<int> NumeroUnico2ID { get; set; }
        public Nullable<int> TallerID { get; set; }
        public Nullable<int> ObreroID { get; set; }
        public Nullable<System.DateTime> FechaArmado { get; set; }
        public Nullable<System.DateTime> FechaReporte { get; set; }
        public Nullable<int> Activo { get; set; }
        public int ActivoUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sam3_JuntaArmadoTrabajoAdicional> sam3_JuntaArmadoTrabajoAdicional { get; set; }
    }
}
