//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_FolioAvisoEntrada
    {
        public Sam3_FolioAvisoEntrada()
        {
            this.Sam3_PackingList = new HashSet<Sam3_PackingList>();
            this.Sam3_FolioPackingList = new HashSet<Sam3_FolioPackingList>();
            this.Sam3_Rel_FolioAvisoEntrada_Proyecto = new HashSet<Sam3_Rel_FolioAvisoEntrada_Proyecto>();
            this.Sam3_Rel_FolioAvisoEntrada_Documento = new HashSet<Sam3_Rel_FolioAvisoEntrada_Documento>();
        }
    
        public int FolioAvisoEntradaID { get; set; }
        public Nullable<int> Consecutivo { get; set; }
        public Nullable<int> FolioAvisoLlegadaID { get; set; }
        public string Estatus { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Factura { get; set; }
        public string OrdenCompra { get; set; }
        public Nullable<int> ProveedorID { get; set; }
        public int ClienteID { get; set; }
        public int PatioID { get; set; }
        public int FolioDescarga { get; set; }
        public Nullable<System.DateTime> FechaFolioDescarga { get; set; }
        public Nullable<System.DateTime> FechaFinDescarga { get; set; }
    
        public virtual ICollection<Sam3_PackingList> Sam3_PackingList { get; set; }
        public virtual Sam3_FolioAvisoLlegada Sam3_FolioAvisoLlegada { get; set; }
        public virtual ICollection<Sam3_FolioPackingList> Sam3_FolioPackingList { get; set; }
        public virtual Sam3_Proveedor Sam3_Proveedor { get; set; }
        public virtual ICollection<Sam3_Rel_FolioAvisoEntrada_Proyecto> Sam3_Rel_FolioAvisoEntrada_Proyecto { get; set; }
        public virtual Sam3_Cliente Sam3_Cliente { get; set; }
        public virtual Sam3_Patio Sam3_Patio { get; set; }
        public virtual ICollection<Sam3_Rel_FolioAvisoEntrada_Documento> Sam3_Rel_FolioAvisoEntrada_Documento { get; set; }
    }
}
