//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Rel_Clasificacion_TipoPrueba
    {
        public int ClasificacionTipoPruebaID { get; set; }
        public int ClasificacionPNDID { get; set; }
        public int TipoPruebaID { get; set; }
        public Nullable<int> Activo { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<bool> RequiereEquipo { get; set; }
        public Nullable<bool> RequiereEntregaDocumento { get; set; }
        public Nullable<bool> RequiereSoldadura { get; set; }
        public Nullable<int> TipoPruebaPorSpool { get; set; }
    }
}
