//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Taller
    {
        public Sam3_Taller()
        {
            this.Sam3_OrdenTrabajo = new HashSet<Sam3_OrdenTrabajo>();
        }
    
        public int TallerID { get; set; }
        public int PatioID { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Sam3_OrdenTrabajo> Sam3_OrdenTrabajo { get; set; }
        public virtual Sam3_Patio Sam3_Patio { get; set; }
    }
}
