//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Rel_Usuario_Preferencia
    {
        public int Rel_Usuario_PreferenciaID { get; set; }
        public int UsuarioID { get; set; }
        public int PreferenciaID { get; set; }
        public string ValorPreferencia { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_Preferencia Sam3_Preferencia { get; set; }
        public virtual Sam3_Usuario Sam3_Usuario { get; set; }
    }
}
