//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_CodigoAsme
    {
        public int ProyectoId { get; set; }
        public string Especificacion { get; set; }
        public string Codigo { get; set; }
        public int TipoPruebaId { get; set; }
        public int Activo { get; set; }
    }
}
