//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_PQR
    {
        public int PQRID { get; set; }
        public string Nombre { get; set; }
        public bool PREHEAT { get; set; }
        public bool PWHT { get; set; }
        public decimal Espesor { get; set; }
        public int ProcesoSoldaduraID { get; set; }
        public Nullable<int> NumeroP { get; set; }
        public Nullable<int> GrupoP { get; set; }
        public Nullable<int> Aporte { get; set; }
        public Nullable<int> Mezcla { get; set; }
        public Nullable<int> Respaldo { get; set; }
        public Nullable<int> GrupoF { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_ProcesoSoldadura Sam3_ProcesoSoldadura { get; set; }
    }
}
