//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Defecto_Juntas
    {
        public int ID_DEFECTO_JUNTA { get; set; }
        public Nullable<int> DefectoID { get; set; }
        public Nullable<int> JuntaID { get; set; }
        public Nullable<int> OrdenTrabajoSpoolID { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_Defecto Sam3_Defecto { get; set; }
        public virtual Sam3_Defecto Sam3_Defecto1 { get; set; }
    }
}
