//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_Rel_Incidencia_Entidad
    {
        public int IncidenciaID { get; set; }
        public int EntidadID { get; set; }
        public bool PermitidoLevantarIncidencias { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_Entidad Sam3_Entidad { get; set; }
        public virtual Sam3_Incidencia Sam3_Incidencia { get; set; }
    }
}
