//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_SP_SpoolAplicable
    {
        public int SpoolAplicableID { get; set; }
        public Nullable<int> OrdenTrabajoID { get; set; }
        public int SpoolID { get; set; }
        public Nullable<int> SistemaPinturaID { get; set; }
        public Nullable<int> SistemaPinturaColorID { get; set; }
        public Nullable<int> SistemaPinturaPaintLineID { get; set; }
        public Nullable<int> SistemaPinturaPaintLineColorID { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
