//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam3_OrdenTrabajoJunta
    {
        public int OrdenTrabajoJuntaID { get; set; }
        public int OrdenTrabajoSpoolID { get; set; }
        public int JuntaSpoolID { get; set; }
        public bool FueReingenieria { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Sam3_JuntaSpool Sam3_JuntaSpool { get; set; }
        public virtual Sam3_OrdenTrabajoSpool Sam3_OrdenTrabajoSpool { get; set; }
    }
}
