//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam_JuntaWorkstatus
    {
        public int JuntaWorkstatusID { get; set; }
        public int OrdenTrabajoSpoolID { get; set; }
        public int JuntaSpoolID { get; set; }
        public string EtiquetaJunta { get; set; }
        public bool ArmadoAprobado { get; set; }
        public bool SoldaduraAprobada { get; set; }
        public bool InspeccionVisualAprobada { get; set; }
        public Nullable<int> JuntaArmadoID { get; set; }
        public Nullable<int> JuntaSoldaduraID { get; set; }
        public Nullable<int> JuntaInspeccionVisualID { get; set; }
        public int VersionJunta { get; set; }
        public Nullable<int> JuntaWorkstatusAnteriorID { get; set; }
        public bool JuntaFinal { get; set; }
        public Nullable<int> UltimoProcesoID { get; set; }
        public bool ArmadoPagado { get; set; }
        public bool SoldaduraPagada { get; set; }
        public Nullable<decimal> TotalPagadoArmado { get; set; }
        public Nullable<decimal> TotalPagadoSoldadura { get; set; }
        public Nullable<decimal> TotalPagado { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
        public string Campo70 { get; set; }
        public string Campo71 { get; set; }
        public string Campo72 { get; set; }
        public string Campo73 { get; set; }
        public string Campo74 { get; set; }
        public string Campo75 { get; set; }
        public string Campo76 { get; set; }
        public string Campo77 { get; set; }
        public string Campo78 { get; set; }
        public string Campo79 { get; set; }
        public string Campo80 { get; set; }
        public string Campo81 { get; set; }
        public string Campo82 { get; set; }
        public string Campo83 { get; set; }
        public string Campo84 { get; set; }
        public string Campo85 { get; set; }
        public string Campo86 { get; set; }
        public string Campo87 { get; set; }
        public string Campo88 { get; set; }
        public string Campo89 { get; set; }
        public string Campo90 { get; set; }
    }
}
