//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sam_OrdenTrabajo
    {
        public int OrdenTrabajoID { get; set; }
        public int EstatusOrdenID { get; set; }
        public int ProyectoID { get; set; }
        public int TallerID { get; set; }
        public string NumeroOrden { get; set; }
        public System.DateTime FechaOrden { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
        public bool EsAsignado { get; set; }
        public Nullable<int> VersionOrden { get; set; }
    }
}
