//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taller
    {
        public Taller()
        {
            this.OrdenTrabajo = new HashSet<OrdenTrabajo>();
        }
    
        public int TallerID { get; set; }
        public int PatioID { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<OrdenTrabajo> OrdenTrabajo { get; set; }
        public virtual Patio Patio { get; set; }
    }
}
