//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMaterial
    {
        public TipoMaterial()
        {
            this.ItemCode = new HashSet<ItemCode>();
        }
    
        public int TipoMaterialID { get; set; }
        public string Nombre { get; set; }
        public string NombreIngles { get; set; }
    
        public virtual ICollection<ItemCode> ItemCode { get; set; }
    }
}
