//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_SP_SpoolAplicable
    {
        public int Accion { get; set; }
        public Nullable<int> SpoolAplicableID { get; set; }
        public Nullable<int> OrdenTrabajoID { get; set; }
        public int SpoolID { get; set; }
        public int SistemaPinturaID { get; set; }
        public int SistemaPinturaColorID { get; set; }
        public Nullable<int> Estatus { get; set; }
    }
}
