//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Bitacora = new HashSet<Bitacora>();
            this.Incidencia = new HashSet<Incidencia>();
            this.Incidencia1 = new HashSet<Incidencia>();
            this.Notificacion = new HashSet<Notificacion>();
            this.Notificacion1 = new HashSet<Notificacion>();
            this.Rel_Documento_Entidad = new HashSet<Rel_Documento_Entidad>();
            this.Rel_Usuario_Proyecto = new HashSet<Rel_Usuario_Proyecto>();
            this.Sesion = new HashSet<Sesion>();
        }
    
        public int UsuarioID { get; set; }
        public int PerfilID { get; set; }
        public string NombreUsuario { get; set; }
        public string ContrasenaHash { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public bool BloqueadoPorAdministracion { get; set; }
        public int EntidadID { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Bitacora> Bitacora { get; set; }
        public virtual Entidad Entidad { get; set; }
        public virtual ICollection<Incidencia> Incidencia { get; set; }
        public virtual ICollection<Incidencia> Incidencia1 { get; set; }
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        public virtual ICollection<Notificacion> Notificacion1 { get; set; }
        public virtual Perfil Perfil { get; set; }
        public virtual ICollection<Rel_Documento_Entidad> Rel_Documento_Entidad { get; set; }
        public virtual ICollection<Rel_Usuario_Proyecto> Rel_Usuario_Proyecto { get; set; }
        public virtual ICollection<Sesion> Sesion { get; set; }
    }
}
