update Sam3_MenuGeneral set liga='#' where Descripcion='Administracion de Catalogos'

insert into Sam3_MenuGeneral values('menuLabel1071','/Catalogos/ListadoCatalogos?catalog=9&leng=',(select menuId from Sam3_MenuGeneral where Descripcion='Administracion de Catalogos'),1,null,null,'',3,'Catalogo Camión',1)
insert into Sam3_MenuGeneral values('menuLabel1072','/Catalogos/ListadoCatalogos?catalog=11&leng=',(select menuId from Sam3_MenuGeneral where Descripcion='Administracion de Catalogos'),1,null,null,'',3,'Catalogo Cédulas',2)
insert into Sam3_MenuGeneral values('menuLabel1073','/Catalogos/ListadoCatalogos?catalog=2&leng=',(select menuId from Sam3_MenuGeneral where Descripcion='Administracion de Catalogos'),1,null,null,'',3,'Catalogo Chofer',3)
insert into Sam3_MenuGeneral values('menuLabel1074','/Catalogos/ListadoCatalogos?catalog=10&leng=',(select menuId from Sam3_MenuGeneral where Descripcion='Administracion de Catalogos'),1,null,null,'',3,'Catalogo Fabricante',4)
insert into Sam3_MenuGeneral values('menuLabel1075','/Catalogos/ListadoCatalogos?catalog=12&leng=',(select menuId from Sam3_MenuGeneral where Descripcion='Administracion de Catalogos'),1,null,null,'',3,'Catalogo MTR',5)
insert into Sam3_MenuGeneral values('menuLabel1076','/Catalogos/ListadoCatalogos?catalog=1&leng=',(select menuId from Sam3_MenuGeneral where Descripcion='Administracion de Catalogos'),1,null,null,'',3,'Catalogo Patios',6)
insert into Sam3_MenuGeneral values('menuLabel1077','/Catalogos/ListadoCatalogos?catalog=6&leng=',(select menuId from Sam3_MenuGeneral where Descripcion='Administracion de Catalogos'),1,null,null,'',3,'Catalogo Plana',7)
insert into Sam3_MenuGeneral values('menuLabel1078','/Catalogos/ListadoCatalogos?catalog=7&leng=',(select menuId from Sam3_MenuGeneral where Descripcion='Administracion de Catalogos'),1,null,null,'',3,'Catalogo Proveedor',8)
insert into Sam3_MenuGeneral values('menuLabel1079','/Catalogos/ListadoCatalogos?catalog=3&leng=',(select menuId from Sam3_MenuGeneral where Descripcion='Administracion de Catalogos'),1,null,null,'',3,'Catalogo Tipo Aviso',9)
insert into Sam3_MenuGeneral values('menuLabel1080','/Catalogos/ListadoCatalogos?catalog=8&leng=',(select menuId from Sam3_MenuGeneral where Descripcion='Administracion de Catalogos'),1,null,null,'',3,'Catalogo Tipo de Uso',10)
insert into Sam3_MenuGeneral values('menuLabel1081','/Catalogos/ListadoCatalogos?catalog=5&leng=',(select menuId from Sam3_MenuGeneral where Descripcion='Administracion de Catalogos'),1,null,null,'',3,'Catalogo Tracto',11)
insert into Sam3_MenuGeneral values('menuLabel1082','/Catalogos/ListadoCatalogos?catalog=4&leng=',(select menuId from Sam3_MenuGeneral where Descripcion='Administracion de Catalogos'),1,null,null,'',3,'Catalogo Transportista',12)


insert into Sam3_Rel_Perfil_MenuGeneral values(1,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Camión'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(1,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Cédulas'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(1,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Chofer'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(1,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Fabricante'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(1,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo MTR'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(1,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Patios'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(1,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Plana'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(1,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Proveedor'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(1,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tipo Aviso'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(1,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tipo de Uso'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(1,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tracto'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(1,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Transportista'),1,null,null)

insert into Sam3_Rel_Perfil_MenuGeneral values(2,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Camión'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(2,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Cédulas'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(2,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Chofer'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(2,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Fabricante'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(2,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo MTR'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(2,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Patios'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(2,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Plana'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(2,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Proveedor'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(2,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tipo Aviso'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(2,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tipo de Uso'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(2,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tracto'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(2,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Transportista'),1,null,null)

insert into Sam3_Rel_Perfil_MenuGeneral values(3,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Camión'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(3,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Cédulas'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(3,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Chofer'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(3,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Fabricante'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(3,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo MTR'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(3,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Patios'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(3,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Plana'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(3,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Proveedor'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(3,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tipo Aviso'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(3,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tipo de Uso'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(3,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tracto'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(3,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Transportista'),1,null,null)

insert into Sam3_Rel_Perfil_MenuGeneral values(4,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Camión'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(4,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Cédulas'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(4,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Chofer'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(4,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Fabricante'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(4,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo MTR'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(4,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Patios'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(4,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Plana'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(4,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Proveedor'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(4,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tipo Aviso'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(4,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tipo de Uso'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(4,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tracto'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(4,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Transportista'),1,null,null)

insert into Sam3_Rel_Perfil_MenuGeneral values(6,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Camión'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(6,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Cédulas'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(6,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Chofer'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(6,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Fabricante'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(6,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo MTR'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(6,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Patios'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(6,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Plana'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(6,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Proveedor'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(6,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tipo Aviso'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(6,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tipo de Uso'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(6,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tracto'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(6,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Transportista'),1,null,null)

insert into Sam3_Rel_Perfil_MenuGeneral values(7,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Camión'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(7,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Cédulas'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(7,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Chofer'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(7,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Fabricante'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(7,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo MTR'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(7,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Patios'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(7,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Plana'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(7,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Proveedor'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(7,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tipo Aviso'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(7,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tipo de Uso'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(7,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Tracto'),1,null,null)
insert into Sam3_Rel_Perfil_MenuGeneral values(7,(select MenuID from Sam3_MenuGeneral where Descripcion='Catalogo Transportista'),1,null,null)

insert into Sam3_Entidad values('Camion',1,null,null)
insert into Sam3_Entidad values('Cedula',1,null,null)
insert into Sam3_Entidad values('Fabricante',1,null,null)
insert into Sam3_Entidad values('MTR',1,null,null)
insert into Sam3_Entidad values('Tipo Aviso',1,null,null)


insert into Sam3_Rel_Perfil_Entidad_Pagina values(1,(select EntidadID from Sam3_Entidad where Nombre ='Camion'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(1,(select EntidadID from Sam3_Entidad where Nombre ='Cedula'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(1,(select EntidadID from Sam3_Entidad where Nombre ='chofer'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(1,(select EntidadID from Sam3_Entidad where Nombre ='Fabricante'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(1,(select EntidadID from Sam3_Entidad where Nombre ='MTR'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(1,(select EntidadID from Sam3_Entidad where Nombre ='Patio'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(1,(select EntidadID from Sam3_Entidad where Nombre ='Plana'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(1,(select EntidadID from Sam3_Entidad where Nombre ='Proveedor'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(1,(select EntidadID from Sam3_Entidad where Nombre ='Tipo Aviso'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(1,(select EntidadID from Sam3_Entidad where Nombre ='Tipo Uso'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(1,(select EntidadID from Sam3_Entidad where Nombre ='Tracto'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(1,(select EntidadID from Sam3_Entidad where Nombre ='Transportista'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)

insert into Sam3_Rel_Perfil_Entidad_Pagina values(2,(select EntidadID from Sam3_Entidad where Nombre ='Camion'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(2,(select EntidadID from Sam3_Entidad where Nombre ='Cedula'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(2,(select EntidadID from Sam3_Entidad where Nombre ='chofer'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(2,(select EntidadID from Sam3_Entidad where Nombre ='Fabricante'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(2,(select EntidadID from Sam3_Entidad where Nombre ='MTR'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(2,(select EntidadID from Sam3_Entidad where Nombre ='Patio'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(2,(select EntidadID from Sam3_Entidad where Nombre ='Plana'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(2,(select EntidadID from Sam3_Entidad where Nombre ='Proveedor'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(2,(select EntidadID from Sam3_Entidad where Nombre ='Tipo Aviso'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(2,(select EntidadID from Sam3_Entidad where Nombre ='Tipo Uso'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(2,(select EntidadID from Sam3_Entidad where Nombre ='Tracto'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(2,(select EntidadID from Sam3_Entidad where Nombre ='Transportista'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)


insert into Sam3_Rel_Perfil_Entidad_Pagina values(3,(select EntidadID from Sam3_Entidad where Nombre ='Camion'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(3,(select EntidadID from Sam3_Entidad where Nombre ='Cedula'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(3,(select EntidadID from Sam3_Entidad where Nombre ='chofer'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(3,(select EntidadID from Sam3_Entidad where Nombre ='Fabricante'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(3,(select EntidadID from Sam3_Entidad where Nombre ='MTR'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(3,(select EntidadID from Sam3_Entidad where Nombre ='Patio'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(3,(select EntidadID from Sam3_Entidad where Nombre ='Plana'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(3,(select EntidadID from Sam3_Entidad where Nombre ='Proveedor'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(3,(select EntidadID from Sam3_Entidad where Nombre ='Tipo Aviso'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(3,(select EntidadID from Sam3_Entidad where Nombre ='Tipo Uso'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(3,(select EntidadID from Sam3_Entidad where Nombre ='Tracto'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(3,(select EntidadID from Sam3_Entidad where Nombre ='Transportista'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)


insert into Sam3_Rel_Perfil_Entidad_Pagina values(4,(select EntidadID from Sam3_Entidad where Nombre ='Camion'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(4,(select EntidadID from Sam3_Entidad where Nombre ='Cedula'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(4,(select EntidadID from Sam3_Entidad where Nombre ='chofer'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(4,(select EntidadID from Sam3_Entidad where Nombre ='Fabricante'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(4,(select EntidadID from Sam3_Entidad where Nombre ='MTR'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(4,(select EntidadID from Sam3_Entidad where Nombre ='Patio'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(4,(select EntidadID from Sam3_Entidad where Nombre ='Plana'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(4,(select EntidadID from Sam3_Entidad where Nombre ='Proveedor'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(4,(select EntidadID from Sam3_Entidad where Nombre ='Tipo Aviso'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(4,(select EntidadID from Sam3_Entidad where Nombre ='Tipo Uso'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(4,(select EntidadID from Sam3_Entidad where Nombre ='Tracto'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(4,(select EntidadID from Sam3_Entidad where Nombre ='Transportista'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)


insert into Sam3_Rel_Perfil_Entidad_Pagina values(6,(select EntidadID from Sam3_Entidad where Nombre ='Camion'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(6,(select EntidadID from Sam3_Entidad where Nombre ='Cedula'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(6,(select EntidadID from Sam3_Entidad where Nombre ='chofer'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(6,(select EntidadID from Sam3_Entidad where Nombre ='Fabricante'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(6,(select EntidadID from Sam3_Entidad where Nombre ='MTR'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(6,(select EntidadID from Sam3_Entidad where Nombre ='Patio'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(6,(select EntidadID from Sam3_Entidad where Nombre ='Plana'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(6,(select EntidadID from Sam3_Entidad where Nombre ='Proveedor'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(6,(select EntidadID from Sam3_Entidad where Nombre ='Tipo Aviso'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(6,(select EntidadID from Sam3_Entidad where Nombre ='Tipo Uso'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(6,(select EntidadID from Sam3_Entidad where Nombre ='Tracto'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(6,(select EntidadID from Sam3_Entidad where Nombre ='Transportista'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)


insert into Sam3_Rel_Perfil_Entidad_Pagina values(7,(select EntidadID from Sam3_Entidad where Nombre ='Camion'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(7,(select EntidadID from Sam3_Entidad where Nombre ='Cedula'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(7,(select EntidadID from Sam3_Entidad where Nombre ='chofer'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(7,(select EntidadID from Sam3_Entidad where Nombre ='Fabricante'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(7,(select EntidadID from Sam3_Entidad where Nombre ='MTR'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(7,(select EntidadID from Sam3_Entidad where Nombre ='Patio'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(7,(select EntidadID from Sam3_Entidad where Nombre ='Plana'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(7,(select EntidadID from Sam3_Entidad where Nombre ='Proveedor'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(7,(select EntidadID from Sam3_Entidad where Nombre ='Tipo Aviso'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(7,(select EntidadID from Sam3_Entidad where Nombre ='Tipo Uso'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(7,(select EntidadID from Sam3_Entidad where Nombre ='Tracto'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)
insert into Sam3_Rel_Perfil_Entidad_Pagina values(7,(select EntidadID from Sam3_Entidad where Nombre ='Transportista'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,1,1,1,1,1,null,null)



insert into Sam3_Propiedad values(( select EntidadID from Sam3_Entidad where Nombre='Cedula'),'factorconversion',1,null,null)
insert into Sam3_Propiedad values(( select EntidadID from Sam3_Entidad where Nombre='Cedula'),'archivos',1,null,null)


insert into Sam3_Rel_Perfil_Propiedad_Pagina values(1,(select PropiedadID from Sam3_Propiedad where EntidadID in( select EntidadID from Sam3_Entidad where Nombre='Cedula') and Nombre='factorconversion'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,0, 1,null,null)
insert into Sam3_Rel_Perfil_Propiedad_Pagina values(1,(select PropiedadID from Sam3_Propiedad where EntidadID in( select EntidadID from Sam3_Entidad where Nombre='Cedula') and Nombre='archivos'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,0,1, null,null)
insert into Sam3_Rel_Perfil_Propiedad_Pagina values(2,(select PropiedadID from Sam3_Propiedad where EntidadID in( select EntidadID from Sam3_Entidad where Nombre='Cedula') and Nombre='factorconversion'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,0, 1,null,null)
insert into Sam3_Rel_Perfil_Propiedad_Pagina values(2,(select PropiedadID from Sam3_Propiedad where EntidadID in( select EntidadID from Sam3_Entidad where Nombre='Cedula') and Nombre='archivos'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,0,1, null,null)
insert into Sam3_Rel_Perfil_Propiedad_Pagina values(3,(select PropiedadID from Sam3_Propiedad where EntidadID in( select EntidadID from Sam3_Entidad where Nombre='Cedula') and Nombre='factorconversion'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,0, 1,null,null)
insert into Sam3_Rel_Perfil_Propiedad_Pagina values(3,(select PropiedadID from Sam3_Propiedad where EntidadID in( select EntidadID from Sam3_Entidad where Nombre='Cedula') and Nombre='archivos'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,0,1, null,null)
insert into Sam3_Rel_Perfil_Propiedad_Pagina values(4,(select PropiedadID from Sam3_Propiedad where EntidadID in( select EntidadID from Sam3_Entidad where Nombre='Cedula') and Nombre='factorconversion'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,0, 1,null,null)
insert into Sam3_Rel_Perfil_Propiedad_Pagina values(4,(select PropiedadID from Sam3_Propiedad where EntidadID in( select EntidadID from Sam3_Entidad where Nombre='Cedula') and Nombre='archivos'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,0,1, null,null)
insert into Sam3_Rel_Perfil_Propiedad_Pagina values(6,(select PropiedadID from Sam3_Propiedad where EntidadID in( select EntidadID from Sam3_Entidad where Nombre='Cedula') and Nombre='factorconversion'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,0, 1,null,null)
insert into Sam3_Rel_Perfil_Propiedad_Pagina values(6,(select PropiedadID from Sam3_Propiedad where EntidadID in( select EntidadID from Sam3_Entidad where Nombre='Cedula') and Nombre='archivos'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,0,1, null,null)
insert into Sam3_Rel_Perfil_Propiedad_Pagina values(7,(select PropiedadID from Sam3_Propiedad where EntidadID in( select EntidadID from Sam3_Entidad where Nombre='Cedula') and Nombre='factorconversion'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,0, 1,null,null)
insert into Sam3_Rel_Perfil_Propiedad_Pagina values(7,(select PropiedadID from Sam3_Propiedad where EntidadID in( select EntidadID from Sam3_Entidad where Nombre='Cedula') and Nombre='archivos'),(select PaginaID from Sam3_Pagina where Accion='ListadoCatalogos'),1,1,0,1, null,null)