//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BastonSpool
    {
        public BastonSpool()
        {
            this.BastonSpoolJunta = new HashSet<BastonSpoolJunta>();
        }
    
        public int BastonSpoolID { get; set; }
        public int SpoolID { get; set; }
        public string LetraBaston { get; set; }
        public Nullable<int> EstacionID { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
        public Nullable<int> TallerID { get; set; }
    
        public virtual Taller Taller { get; set; }
        public virtual Estacion Estacion { get; set; }
        public virtual Spool Spool { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<BastonSpoolJunta> BastonSpoolJunta { get; set; }
    }
}
