//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionArmadoMaterial
    {
        public int ConfiguracionArmadoMaterialId { get; set; }
        public int MaterialID { get; set; }
        public decimal Multiplicador { get; set; }
        public Nullable<int> ProcesoID { get; set; }
        public Nullable<int> TipoJuntaID { get; set; }
        public Nullable<int> ProcesoRellenoID { get; set; }
    }
}
