//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuadranteHistorico
    {
        public int CuadranteHistoricoID { get; set; }
        public int SpoolID { get; set; }
        public int CuadranteID { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual Cuadrante Cuadrante { get; set; }
        public virtual Spool Spool { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
