//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despacho
    {
        public Despacho()
        {
            this.OrdenTrabajoMaterial = new HashSet<OrdenTrabajoMaterial>();
        }
    
        public int DespachoID { get; set; }
        public int ProyectoID { get; set; }
        public int OrdenTrabajoSpoolID { get; set; }
        public int MaterialSpoolID { get; set; }
        public int NumeroUnicoID { get; set; }
        public Nullable<int> SalidaInventarioID { get; set; }
        public string Segmento { get; set; }
        public bool EsEquivalente { get; set; }
        public int Cantidad { get; set; }
        public bool Cancelado { get; set; }
        public System.DateTime FechaDespacho { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
        public Nullable<int> DespachadorID { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual MaterialSpool MaterialSpool { get; set; }
        public virtual NumeroUnico NumeroUnico { get; set; }
        public virtual NumeroUnicoMovimiento NumeroUnicoMovimiento { get; set; }
        public virtual OrdenTrabajoSpool OrdenTrabajoSpool { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual ICollection<OrdenTrabajoMaterial> OrdenTrabajoMaterial { get; set; }
    }
}
