//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestajoTuberoDetalle
    {
        public int DestajoTuberoDetalleID { get; set; }
        public int DestajoTuberoID { get; set; }
        public int JuntaWorkstatusID { get; set; }
        public int ProyectoID { get; set; }
        public decimal PDIs { get; set; }
        public decimal CostoUnitario { get; set; }
        public decimal Destajo { get; set; }
        public decimal ProrrateoCuadro { get; set; }
        public decimal ProrrateoDiasFestivos { get; set; }
        public decimal ProrrateoOtros { get; set; }
        public decimal Ajuste { get; set; }
        public decimal Total { get; set; }
        public string Comentarios { get; set; }
        public bool EsDePeriodoAnterior { get; set; }
        public bool CostoDestajoVacio { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual DestajoTubero DestajoTubero { get; set; }
        public virtual JuntaWorkstatus JuntaWorkstatus { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
