//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestajoTubero
    {
        public DestajoTubero()
        {
            this.DestajoTuberoDetalle = new HashSet<DestajoTuberoDetalle>();
        }
    
        public int DestajoTuberoID { get; set; }
        public int TuberoID { get; set; }
        public int PeriodoDestajoID { get; set; }
        public decimal ReferenciaCuadro { get; set; }
        public int CantidadDiasFestivos { get; set; }
        public decimal CostoDiaFestivo { get; set; }
        public decimal TotalDestajo { get; set; }
        public decimal TotalCuadro { get; set; }
        public decimal TotalDiasFestivos { get; set; }
        public decimal TotalOtros { get; set; }
        public decimal TotalAjuste { get; set; }
        public decimal GranTotal { get; set; }
        public bool Aprobado { get; set; }
        public string Comentarios { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual PeriodoDestajo PeriodoDestajo { get; set; }
        public virtual Tubero Tubero { get; set; }
        public virtual ICollection<DestajoTuberoDetalle> DestajoTuberoDetalle { get; set; }
    }
}
