//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePersonalizacionSeguimientoJunta
    {
        public int DetallePersonalizacionSeguimientoJuntaID { get; set; }
        public int PersonalizacionSeguimientoJuntaID { get; set; }
        public int CampoSeguimientoJuntaID { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual CampoSeguimientoJunta CampoSeguimientoJunta { get; set; }
        public virtual PersonalizacionSeguimientoJunta PersonalizacionSeguimientoJunta { get; set; }
    }
}
