//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamiliaAcero
    {
        public FamiliaAcero()
        {
            this.Acero = new HashSet<Acero>();
            this.CostoArmado = new HashSet<CostoArmado>();
            this.CostoProcesoRaiz = new HashSet<CostoProcesoRaiz>();
            this.CostoProcesoRelleno = new HashSet<CostoProcesoRelleno>();
            this.ItemCode = new HashSet<ItemCode>();
            this.JuntaSpool = new HashSet<JuntaSpool>();
            this.JuntaSpool1 = new HashSet<JuntaSpool>();
            this.JuntaSpoolPendiente = new HashSet<JuntaSpoolPendiente>();
            this.JuntaSpoolPendiente1 = new HashSet<JuntaSpoolPendiente>();
            this.Peq = new HashSet<Peq>();
            this.Spool = new HashSet<Spool>();
            this.Spool1 = new HashSet<Spool>();
            this.SpoolPendiente = new HashSet<SpoolPendiente>();
            this.SpoolPendiente1 = new HashSet<SpoolPendiente>();
            this.Wps = new HashSet<Wps>();
            this.Wps1 = new HashSet<Wps>();
        }
    
        public int FamiliaAceroID { get; set; }
        public int FamiliaMaterialID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool VerificadoPorCalidad { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual ICollection<Acero> Acero { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<CostoArmado> CostoArmado { get; set; }
        public virtual ICollection<CostoProcesoRaiz> CostoProcesoRaiz { get; set; }
        public virtual ICollection<CostoProcesoRelleno> CostoProcesoRelleno { get; set; }
        public virtual FamiliaMaterial FamiliaMaterial { get; set; }
        public virtual ICollection<ItemCode> ItemCode { get; set; }
        public virtual ICollection<JuntaSpool> JuntaSpool { get; set; }
        public virtual ICollection<JuntaSpool> JuntaSpool1 { get; set; }
        public virtual ICollection<JuntaSpoolPendiente> JuntaSpoolPendiente { get; set; }
        public virtual ICollection<JuntaSpoolPendiente> JuntaSpoolPendiente1 { get; set; }
        public virtual ICollection<Peq> Peq { get; set; }
        public virtual ICollection<Spool> Spool { get; set; }
        public virtual ICollection<Spool> Spool1 { get; set; }
        public virtual ICollection<SpoolPendiente> SpoolPendiente { get; set; }
        public virtual ICollection<SpoolPendiente> SpoolPendiente1 { get; set; }
        public virtual ICollection<Wps> Wps { get; set; }
        public virtual ICollection<Wps> Wps1 { get; set; }
    }
}
