//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrentePintura
    {
        public FrentePintura()
        {
            this.PinturaCondicionesAmbientales = new HashSet<PinturaCondicionesAmbientales>();
        }
    
        public int FrentePinturaID { get; set; }
        public string Nombre { get; set; }
        public int Activo { get; set; }
    
        public virtual ICollection<PinturaCondicionesAmbientales> PinturaCondicionesAmbientales { get; set; }
    }
}
