//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Isolog
    {
        public string SPOOL_NAME { get; set; }
        public string REF_DWGS { get; set; }
        public string LINE_NO { get; set; }
        public string DRAWING_NUMBER { get; set; }
        public Nullable<decimal> DIAMETER { get; set; }
        public string Mat { get; set; }
        public string SYSTEM { get; set; }
        public string SPEC_CODE { get; set; }
        public string PROJ { get; set; }
        public Nullable<int> SH { get; set; }
        public Nullable<int> SHTT { get; set; }
        public Nullable<int> NO_SH_TT { get; set; }
        public string DA { get; set; }
        public Nullable<int> SPOOL { get; set; }
        public string COST_CODE { get; set; }
        public string PW_POST_DATE { get; set; }
        public string ISO_LIST_REV { get; set; }
        public Nullable<int> ULTIMA_REV { get; set; }
        public Nullable<System.DateTime> RRD_0 { get; set; }
        public Nullable<System.DateTime> RRD_1 { get; set; }
        public Nullable<System.DateTime> RRD_2 { get; set; }
        public Nullable<System.DateTime> RRD_3 { get; set; }
        public Nullable<System.DateTime> RRD_4 { get; set; }
        public Nullable<int> RRD_REV_CONT { get; set; }
        public Nullable<System.DateTime> APC { get; set; }
        public Nullable<System.DateTime> IDF { get; set; }
        public string Transmittal_1 { get; set; }
        public string Transmittal_2 { get; set; }
        public string Transmittal_3 { get; set; }
        public string P1_SHOP_REV { get; set; }
        public Nullable<System.DateTime> P1_FECHA_PROCESADO_IDF { get; set; }
        public string P2_SHOP_REV { get; set; }
        public Nullable<System.DateTime> P2_FECHA_PROCESADO_IDF { get; set; }
        public string P3_SHOP_REV { get; set; }
        public Nullable<System.DateTime> P3_FECHA_PROCESADO_IDF { get; set; }
        public string FIX_REQ { get; set; }
        public string RESEND { get; set; }
        public string AS_BUILT { get; set; }
        public string FIELD_VOID { get; set; }
        public string HOLD { get; set; }
        public string DATE_HOLD { get; set; }
        public string DATE_HOLD_RELEASE { get; set; }
        public Nullable<int> Sem { get; set; }
        public Nullable<int> Prioridad { get; set; }
    }
}
