//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsoPrioridadEtileno
    {
        public string SpoolNombre { get; set; }
        public string Dibujo { get; set; }
        public string RespErection { get; set; }
        public string DesSistema { get; set; }
        public Nullable<int> Iso { get; set; }
        public Nullable<int> Unit { get; set; }
        public string spool { get; set; }
        public string Recibimiento { get; set; }
        public string PrioridadEmbarque { get; set; }
        public string FechaPrevistePintura { get; set; }
        public string FechaPrvistaEmbarque { get; set; }
        public Nullable<decimal> Peso { get; set; }
    }
}
