//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCode
    {
        public ItemCode()
        {
            this.CorteSpool = new HashSet<CorteSpool>();
            this.CorteSpoolPendiente = new HashSet<CorteSpoolPendiente>();
            this.ReservaItemcode = new HashSet<ReservaItemcode>();
            this.ItemCodeEquivalente = new HashSet<ItemCodeEquivalente>();
            this.ItemCodeEquivalente1 = new HashSet<ItemCodeEquivalente>();
            this.MaterialSpool = new HashSet<MaterialSpool>();
            this.MaterialSpoolPendiente = new HashSet<MaterialSpoolPendiente>();
            this.NumeroUnico = new HashSet<NumeroUnico>();
        }
    
        public int ItemCodeID { get; set; }
        public int ProyectoID { get; set; }
        public int TipoMaterialID { get; set; }
        public string Codigo { get; set; }
        public string ItemCodeCliente { get; set; }
        public string DescripcionEspanol { get; set; }
        public string DescripcionIngles { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string DescripcionInterna { get; set; }
        public Nullable<decimal> Diametro1 { get; set; }
        public Nullable<decimal> Diametro2 { get; set; }
        public Nullable<int> FamiliaAceroID { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<CorteSpool> CorteSpool { get; set; }
        public virtual ICollection<CorteSpoolPendiente> CorteSpoolPendiente { get; set; }
        public virtual FamiliaAcero FamiliaAcero { get; set; }
        public virtual ICollection<ReservaItemcode> ReservaItemcode { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual TipoMaterial TipoMaterial { get; set; }
        public virtual ICollection<ItemCodeEquivalente> ItemCodeEquivalente { get; set; }
        public virtual ICollection<ItemCodeEquivalente> ItemCodeEquivalente1 { get; set; }
        public virtual ICollection<MaterialSpool> MaterialSpool { get; set; }
        public virtual ICollection<MaterialSpoolPendiente> MaterialSpoolPendiente { get; set; }
        public virtual ICollection<NumeroUnico> NumeroUnico { get; set; }
    }
}
