//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JuntaArmado
    {
        public JuntaArmado()
        {
            this.JuntaWorkstatus1 = new HashSet<JuntaWorkstatus>();
        }
    
        public int JuntaArmadoID { get; set; }
        public int JuntaWorkstatusID { get; set; }
        public Nullable<int> NumeroUnico1ID { get; set; }
        public Nullable<int> NumeroUnico2ID { get; set; }
        public int TallerID { get; set; }
        public int TuberoID { get; set; }
        public System.DateTime FechaArmado { get; set; }
        public System.DateTime FechaReporte { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual JuntaWorkstatus JuntaWorkstatus { get; set; }
        public virtual NumeroUnico NumeroUnico { get; set; }
        public virtual NumeroUnico NumeroUnico1 { get; set; }
        public virtual Taller Taller { get; set; }
        public virtual Tubero Tubero { get; set; }
        public virtual ICollection<JuntaWorkstatus> JuntaWorkstatus1 { get; set; }
    }
}
