//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JuntaRequisicion
    {
        public JuntaRequisicion()
        {
            this.JuntaReportePnd = new HashSet<JuntaReportePnd>();
            this.JuntaReporteTt = new HashSet<JuntaReporteTt>();
        }
    
        public int JuntaRequisicionID { get; set; }
        public int RequisicionID { get; set; }
        public int JuntaWorkstatusID { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
        public string NumPreliminar { get; set; }
        public string Fuente { get; set; }
        public string Turno { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Toma { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<JuntaReportePnd> JuntaReportePnd { get; set; }
        public virtual ICollection<JuntaReporteTt> JuntaReporteTt { get; set; }
        public virtual JuntaWorkstatus JuntaWorkstatus { get; set; }
        public virtual Requisicion Requisicion { get; set; }
    }
}
