//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JuntaReportePndCuadrante
    {
        public int JuntaReportePndCuadranteID { get; set; }
        public int JuntaReportePndID { get; set; }
        public string Cuadrante { get; set; }
        public string Placa { get; set; }
        public Nullable<int> DefectoID { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
        public Nullable<int> SoldadorID { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Defecto Defecto { get; set; }
        public virtual JuntaReportePnd JuntaReportePnd { get; set; }
        public virtual Soldador Soldador { get; set; }
    }
}
