//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JuntaCampoArmado
    {
        public JuntaCampoArmado()
        {
            this.JuntaCampo = new HashSet<JuntaCampo>();
        }
    
        public int JuntaCampoArmadoID { get; set; }
        public int JuntaCampoID { get; set; }
        public int Spool1ID { get; set; }
        public string EtiquetaMaterial1 { get; set; }
        public int NumeroUnico1ID { get; set; }
        public int Spool2ID { get; set; }
        public string EtiquetaMaterial2 { get; set; }
        public int NumeroUnico2ID { get; set; }
        public int TuberoID { get; set; }
        public System.DateTime FechaArmado { get; set; }
        public System.DateTime FechaReporte { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<JuntaCampo> JuntaCampo { get; set; }
        public virtual JuntaCampo JuntaCampo1 { get; set; }
        public virtual NumeroUnico NumeroUnico { get; set; }
        public virtual NumeroUnico NumeroUnico1 { get; set; }
        public virtual Spool Spool { get; set; }
        public virtual Spool Spool1 { get; set; }
        public virtual Tubero Tubero { get; set; }
    }
}
