//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JuntaCampoReportePND
    {
        public JuntaCampoReportePND()
        {
            this.JuntaCampoReportePNDCuadrante = new HashSet<JuntaCampoReportePNDCuadrante>();
            this.JuntaCampoReportePNDSector = new HashSet<JuntaCampoReportePNDSector>();
        }
    
        public int JuntaCampoReportePNDID { get; set; }
        public int ReporteCampoPNDID { get; set; }
        public int JuntaCampoID { get; set; }
        public int JuntaCampoRequisicionID { get; set; }
        public Nullable<int> TipoRechazoID { get; set; }
        public System.DateTime FechaPrueba { get; set; }
        public bool Aprobado { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual JuntaCampo JuntaCampo { get; set; }
        public virtual JuntaCampoRequisicion JuntaCampoRequisicion { get; set; }
        public virtual ReporteCampoPND ReporteCampoPND { get; set; }
        public virtual TipoRechazo TipoRechazo { get; set; }
        public virtual ICollection<JuntaCampoReportePNDCuadrante> JuntaCampoReportePNDCuadrante { get; set; }
        public virtual ICollection<JuntaCampoReportePNDSector> JuntaCampoReportePNDSector { get; set; }
    }
}
