//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maquina
    {
        public Maquina()
        {
            this.CorteDetalle = new HashSet<CorteDetalle>();
        }
    
        public int MaquinaID { get; set; }
        public int PatioID { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
        public Nullable<int> MermaTeorica { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<CorteDetalle> CorteDetalle { get; set; }
        public virtual Patio Patio { get; set; }
    }
}
