//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptEntregaOrdenesTrabajo
    {
        public int OrdenTrabajoSpoolID { get; set; }
        public string Material { get; set; }
        public string FabLineTEXT { get; set; }
        public Nullable<int> FabLine { get; set; }
        public string TopDiametros { get; set; }
        public Nullable<decimal> Pdis { get; set; }
        public Nullable<decimal> PeqSpool { get; set; }
    }
}
