//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptProgramacionOT
    {
        public int OrdenTrabajoID { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public string Reserva { get; set; }
        public Nullable<int> Spools { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Peqs { get; set; }
        public Nullable<int> Corte { get; set; }
        public Nullable<int> Armado { get; set; }
        public Nullable<int> Soldadura { get; set; }
        public Nullable<System.DateTime> FechaPrevSoldadura { get; set; }
        public Nullable<System.DateTime> FechaTerminacion { get; set; }
        public string Observaciones { get; set; }
    }
}
