//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptReporteFaltantes
    {
        public int ProyectoID { get; set; }
        public int ReporteID { get; set; }
        public string ReporteFaltantesID { get; set; }
        public string Campo1 { get; set; }
        public Nullable<int> Hold { get; set; }
        public Nullable<int> Materiales { get; set; }
        public Nullable<int> Despacho { get; set; }
        public Nullable<int> Armado { get; set; }
        public Nullable<int> Soldadura { get; set; }
        public Nullable<int> Visual { get; set; }
        public Nullable<int> Dimensional { get; set; }
        public Nullable<int> DigRT { get; set; }
        public Nullable<int> DigPT { get; set; }
        public Nullable<int> DigDUR { get; set; }
        public Nullable<int> DigPMI { get; set; }
        public Nullable<int> PWHT { get; set; }
        public Nullable<int> Pintura { get; set; }
    }
}
