//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenTrabajoSpool
    {
        public OrdenTrabajoSpool()
        {
            this.CorteDetalle = new HashSet<CorteDetalle>();
            this.Despacho = new HashSet<Despacho>();
            this.JuntaCampo = new HashSet<JuntaCampo>();
            this.JuntaWorkstatus = new HashSet<JuntaWorkstatus>();
            this.OrdenTrabajoJunta = new HashSet<OrdenTrabajoJunta>();
            this.OrdenTrabajoMaterial = new HashSet<OrdenTrabajoMaterial>();
            this.WorkstatusSpool = new HashSet<WorkstatusSpool>();
            this.PreList = new HashSet<PreList>();
        }
    
        public int OrdenTrabajoSpoolID { get; set; }
        public int OrdenTrabajoID { get; set; }
        public int SpoolID { get; set; }
        public int Partida { get; set; }
        public string NumeroControl { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
        public bool EsAsignado { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<CorteDetalle> CorteDetalle { get; set; }
        public virtual ICollection<Despacho> Despacho { get; set; }
        public virtual ICollection<JuntaCampo> JuntaCampo { get; set; }
        public virtual ICollection<JuntaWorkstatus> JuntaWorkstatus { get; set; }
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
        public virtual ICollection<OrdenTrabajoJunta> OrdenTrabajoJunta { get; set; }
        public virtual ICollection<OrdenTrabajoMaterial> OrdenTrabajoMaterial { get; set; }
        public virtual Spool Spool { get; set; }
        public virtual ICollection<WorkstatusSpool> WorkstatusSpool { get; set; }
        public virtual ICollection<PreList> PreList { get; set; }
    }
}
