//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patio
    {
        public Patio()
        {
            this.Consumible = new HashSet<Consumible>();
            this.Cortador = new HashSet<Cortador>();
            this.Cuadrante = new HashSet<Cuadrante>();
            this.Despachador = new HashSet<Despachador>();
            this.Destino = new HashSet<Destino>();
            this.Inspector = new HashSet<Inspector>();
            this.Maquina = new HashSet<Maquina>();
            this.Proyecto = new HashSet<Proyecto>();
            this.Soldador = new HashSet<Soldador>();
            this.Taller = new HashSet<Taller>();
            this.Tubero = new HashSet<Tubero>();
            this.UbicacionFisica = new HashSet<UbicacionFisica>();
        }
    
        public int PatioID { get; set; }
        public string Nombre { get; set; }
        public string Propietario { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<Consumible> Consumible { get; set; }
        public virtual ICollection<Cortador> Cortador { get; set; }
        public virtual ICollection<Cuadrante> Cuadrante { get; set; }
        public virtual ICollection<Despachador> Despachador { get; set; }
        public virtual ICollection<Destino> Destino { get; set; }
        public virtual ICollection<Inspector> Inspector { get; set; }
        public virtual ICollection<Maquina> Maquina { get; set; }
        public virtual ICollection<Proyecto> Proyecto { get; set; }
        public virtual ICollection<Soldador> Soldador { get; set; }
        public virtual ICollection<Taller> Taller { get; set; }
        public virtual ICollection<Tubero> Tubero { get; set; }
        public virtual ICollection<UbicacionFisica> UbicacionFisica { get; set; }
    }
}
