//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinturaReporteInspeccion
    {
        public int PinturaReporteInspeccionID { get; set; }
        public string NumeroReporte { get; set; }
        public Nullable<System.DateTime> FechaReporte { get; set; }
        public string NumeroAparato { get; set; }
        public string Img1 { get; set; }
        public string Img2 { get; set; }
        public string Img3 { get; set; }
        public string Img4 { get; set; }
        public string ComentarioImg1 { get; set; }
        public string ComentarioImg2 { get; set; }
        public string ComentarioImg3 { get; set; }
        public string ComentarioImg4 { get; set; }
        public Nullable<int> CondicionesAmbientalesID { get; set; }
    }
}
