//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinturaCondicionesAmbientales
    {
        public int PinturaCondicionesAmbientalesID { get; set; }
        public Nullable<int> FrentePinturaID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> TemperaturaSustrato { get; set; }
        public Nullable<decimal> TemperaturaAmbiental { get; set; }
        public Nullable<decimal> HumedadRelativa { get; set; }
        public Nullable<decimal> PuntoRocio { get; set; }
        public Nullable<decimal> VerifCalidadAire { get; set; }
        public Nullable<decimal> PruebaClorurosAceiteAbra { get; set; }
    
        public virtual FrentePintura FrentePintura { get; set; }
    }
}
