//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinturaAvance
    {
        public int PinturaAvanceID { get; set; }
        public int ProyectoID { get; set; }
        public Nullable<int> WorkstatusSpoolID { get; set; }
        public Nullable<int> RequisicionPinturaDetalleID { get; set; }
        public int ProcesoPinturaID { get; set; }
        public Nullable<decimal> C1 { get; set; }
        public Nullable<decimal> C2 { get; set; }
        public Nullable<decimal> C3 { get; set; }
        public Nullable<decimal> C4 { get; set; }
        public Nullable<decimal> C5 { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
        public virtual RequisicionPinturaDetalle RequisicionPinturaDetalle { get; set; }
        public virtual WorkstatusSpool WorkstatusSpool { get; set; }
    }
}
