//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcesoRelleno
    {
        public ProcesoRelleno()
        {
            this.CostoProcesoRelleno = new HashSet<CostoProcesoRelleno>();
            this.JuntaCampoSoldadura = new HashSet<JuntaCampoSoldadura>();
            this.JuntaSoldadura = new HashSet<JuntaSoldadura>();
            this.Wps = new HashSet<Wps>();
        }
    
        public int ProcesoRellenoID { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string NombreIngles { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<CostoProcesoRelleno> CostoProcesoRelleno { get; set; }
        public virtual ICollection<JuntaCampoSoldadura> JuntaCampoSoldadura { get; set; }
        public virtual ICollection<JuntaSoldadura> JuntaSoldadura { get; set; }
        public virtual ICollection<Wps> Wps { get; set; }
    }
}
