//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoDossier
    {
        public int ProyectoID { get; set; }
        public bool ReporteInspeccionVisual { get; set; }
        public bool ReporteLiberacionDimensional { get; set; }
        public bool ReporteEspesores { get; set; }
        public bool ReporteRT { get; set; }
        public bool ReportePT { get; set; }
        public bool ReportePwht { get; set; }
        public bool ReporteDurezas { get; set; }
        public bool ReporteRTPostTT { get; set; }
        public bool ReportePTPostTT { get; set; }
        public bool ReportePreheat { get; set; }
        public bool ReporteUT { get; set; }
        public bool ReportesPintura { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
        public bool Trazabilidad { get; set; }
        public bool WPS { get; set; }
        public bool Embarque { get; set; }
        public bool MTR { get; set; }
        public bool MTRCertificado { get; set; }
        public bool LDCertificado { get; set; }
        public bool MTRSoldadura { get; set; }
        public bool Drawing { get; set; }
        public bool ReportePMI { get; set; }
        public Nullable<bool> ReportePruebaHidrostatica { get; set; }
        public bool TrazabilidadCertificado { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
    }
}
