//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteCampoTT
    {
        public ReporteCampoTT()
        {
            this.JuntaCampoReporteTT = new HashSet<JuntaCampoReporteTT>();
        }
    
        public int ReporteCampoTTID { get; set; }
        public int ProyectoID { get; set; }
        public int TipoPruebaID { get; set; }
        public string NumeroReporte { get; set; }
        public System.DateTime FechaReporte { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual ICollection<JuntaCampoReporteTT> JuntaCampoReporteTT { get; set; }
    }
}
