//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisicion
    {
        public Requisicion()
        {
            this.JuntaRequisicion = new HashSet<JuntaRequisicion>();
        }
    
        public int RequisicionID { get; set; }
        public int ProyectoID { get; set; }
        public Nullable<int> TipoPruebaID { get; set; }
        public System.DateTime FechaRequisicion { get; set; }
        public string NumeroRequisicion { get; set; }
        public string CodigoAsme { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<JuntaRequisicion> JuntaRequisicion { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual TipoPrueba TipoPrueba { get; set; }
    }
}
