//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaItemcode
    {
        public int ReservaID { get; set; }
        public int ItemCodeID { get; set; }
        public int SpoolID { get; set; }
    
        public virtual ItemCode ItemCode { get; set; }
        public virtual Reserva Reserva { get; set; }
        public virtual Spool Spool { get; set; }
    }
}
