//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAC_Temp_BHTInventario
    {
        public int ID_Inventario { get; set; }
        public Nullable<int> ID_BHTecnip { get; set; }
        public string ControlNO { get; set; }
        public Nullable<double> CantidadAsignada { get; set; }
    }
}
