//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistemaPinturaConfig
    {
        public int ProyectoID { get; set; }
        public int SistemaPinturaID { get; set; }
        public string TemperaturaOperacion { get; set; }
        public string PreparacionSuperficie { get; set; }
        public string PrimariosEspesorPelicula { get; set; }
        public int AplicaPrimarios { get; set; }
        public string PrimariosTipoProducto { get; set; }
        public int AplicaIntermedios { get; set; }
        public string IntermediosEspesorPelicula { get; set; }
        public string IntermediosTipoProducto { get; set; }
        public int AplicaAcabadoVisual { get; set; }
        public string AcabadoEspesorPelicula { get; set; }
        public string AcabadoTipoProducto { get; set; }
        public string ColorAcabado { get; set; }
        public string UnidadMedidaEspesores { get; set; }
        public string ProfundidadAnclajeRequerido { get; set; }
    }
}
