//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spool
    {
        public Spool()
        {
            this.AgrupadoresSpoolPND = new HashSet<AgrupadoresSpoolPND>();
            this.BastonSpool = new HashSet<BastonSpool>();
            this.CorteSpool = new HashSet<CorteSpool>();
            this.CuadranteHistorico = new HashSet<CuadranteHistorico>();
            this.HistoricoWorkstatus = new HashSet<HistoricoWorkstatus>();
            this.JuntaCampoArmado = new HashSet<JuntaCampoArmado>();
            this.JuntaCampoArmado1 = new HashSet<JuntaCampoArmado>();
            this.JuntaSpool = new HashSet<JuntaSpool>();
            this.MaterialSpool = new HashSet<MaterialSpool>();
            this.OrdenTrabajoSpool = new HashSet<OrdenTrabajoSpool>();
            this.ReservaItemcode = new HashSet<ReservaItemcode>();
            this.SpoolHoldHistorial = new HashSet<SpoolHoldHistorial>();
            this.TransferenciaSpool = new HashSet<TransferenciaSpool>();
        }
    
        public int SpoolID { get; set; }
        public int ProyectoID { get; set; }
        public int FamiliaAcero1ID { get; set; }
        public Nullable<int> FamiliaAcero2ID { get; set; }
        public string Nombre { get; set; }
        public string Dibujo { get; set; }
        public string Especificacion { get; set; }
        public string Cedula { get; set; }
        public Nullable<decimal> Pdis { get; set; }
        public Nullable<decimal> DiametroPlano { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<int> PorcentajePnd { get; set; }
        public bool RequierePwht { get; set; }
        public bool PendienteDocumental { get; set; }
        public bool AprobadoParaCruce { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public string Revision { get; set; }
        public string RevisionCliente { get; set; }
        public string Segmento1 { get; set; }
        public string Segmento2 { get; set; }
        public string Segmento3 { get; set; }
        public string Segmento4 { get; set; }
        public string Segmento5 { get; set; }
        public string Segmento6 { get; set; }
        public string Segmento7 { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
        public string SistemaPintura { get; set; }
        public string ColorPintura { get; set; }
        public string CodigoPintura { get; set; }
        public Nullable<System.DateTime> FechaEtiqueta { get; set; }
        public string NumeroEtiqueta { get; set; }
        public string Campo1 { get; set; }
        public string Campo2 { get; set; }
        public string Campo3 { get; set; }
        public string Campo4 { get; set; }
        public string Campo5 { get; set; }
        public Nullable<decimal> DiametroMayor { get; set; }
        public Nullable<int> CuadranteID { get; set; }
        public Nullable<System.DateTime> FechaImportacion { get; set; }
        public string RequierePruebaHidrostatica { get; set; }
        public Nullable<System.DateTime> FechaLocalizacion { get; set; }
        public string UltimoProceso { get; set; }
        public string AreaGrupo { get; set; }
        public string KgsGrupo { get; set; }
        public string DiamGrupo { get; set; }
        public string PeqGrupo { get; set; }
        public string SistemaPinturaFinal { get; set; }
        public string Paint { get; set; }
        public string DiametroPromedio { get; set; }
        public string PaintLine { get; set; }
        public string AreaEq { get; set; }
        public string Inox { get; set; }
        public string ClasifInox { get; set; }
        public Nullable<System.DateTime> FechaHomologacion { get; set; }
        public string Campo6 { get; set; }
        public string Campo7 { get; set; }
        public string Campo8 { get; set; }
        public string Campo9 { get; set; }
        public string Campo10 { get; set; }
        public string Campo11 { get; set; }
        public string Campo12 { get; set; }
        public string Campo13 { get; set; }
        public string Campo14 { get; set; }
        public string Campo15 { get; set; }
        public string Campo16 { get; set; }
        public string Campo17 { get; set; }
        public string Campo18 { get; set; }
        public string Campo19 { get; set; }
        public string Campo20 { get; set; }
        public string Campo21 { get; set; }
        public string Campo22 { get; set; }
        public string Campo23 { get; set; }
        public string Campo24 { get; set; }
        public string Campo25 { get; set; }
        public string Campo26 { get; set; }
        public string Campo27 { get; set; }
        public string Campo28 { get; set; }
        public string Campo29 { get; set; }
        public string Campo30 { get; set; }
        public string Campo31 { get; set; }
        public string Campo32 { get; set; }
        public string Campo33 { get; set; }
        public string Campo34 { get; set; }
        public string Campo35 { get; set; }
        public string Campo36 { get; set; }
        public string Campo37 { get; set; }
        public string Campo38 { get; set; }
        public string Campo39 { get; set; }
        public string Campo40 { get; set; }
        public string Campo41 { get; set; }
        public string Campo42 { get; set; }
        public string Campo43 { get; set; }
        public string Campo44 { get; set; }
        public string Campo45 { get; set; }
        public string Campo46 { get; set; }
        public string Campo47 { get; set; }
        public string Campo48 { get; set; }
        public string Campo49 { get; set; }
        public string Campo50 { get; set; }
        public string Campo51 { get; set; }
        public string Campo52 { get; set; }
        public string Campo53 { get; set; }
        public string Campo54 { get; set; }
        public string Campo55 { get; set; }
        public string Campo56 { get; set; }
        public string Campo57 { get; set; }
        public string Campo58 { get; set; }
        public string Campo59 { get; set; }
        public string Campo60 { get; set; }
        public string Campo61 { get; set; }
        public string Campo62 { get; set; }
        public string Campo63 { get; set; }
        public string Campo64 { get; set; }
        public string Campo65 { get; set; }
        public string Campo66 { get; set; }
        public string Campo67 { get; set; }
        public string Campo68 { get; set; }
        public string Campo69 { get; set; }
        public string Campo70 { get; set; }
        public string Campo71 { get; set; }
        public string Campo72 { get; set; }
        public string Campo73 { get; set; }
        public string Campo74 { get; set; }
        public string Campo75 { get; set; }
    
        public virtual ICollection<AgrupadoresSpoolPND> AgrupadoresSpoolPND { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<BastonSpool> BastonSpool { get; set; }
        public virtual ICollection<CorteSpool> CorteSpool { get; set; }
        public virtual ICollection<CuadranteHistorico> CuadranteHistorico { get; set; }
        public virtual FamiliaAcero FamiliaAcero { get; set; }
        public virtual FamiliaAcero FamiliaAcero1 { get; set; }
        public virtual ICollection<HistoricoWorkstatus> HistoricoWorkstatus { get; set; }
        public virtual ICollection<JuntaCampoArmado> JuntaCampoArmado { get; set; }
        public virtual ICollection<JuntaCampoArmado> JuntaCampoArmado1 { get; set; }
        public virtual ICollection<JuntaSpool> JuntaSpool { get; set; }
        public virtual ICollection<MaterialSpool> MaterialSpool { get; set; }
        public virtual ICollection<OrdenTrabajoSpool> OrdenTrabajoSpool { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual ICollection<ReservaItemcode> ReservaItemcode { get; set; }
        public virtual SpoolHold SpoolHold { get; set; }
        public virtual ICollection<SpoolHoldHistorial> SpoolHoldHistorial { get; set; }
        public virtual ICollection<TransferenciaSpool> TransferenciaSpool { get; set; }
    }
}
