//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusEmbarque
    {
        public int SpoolID { get; set; }
        public Nullable<long> IndexNC { get; set; }
        public string NumeroControl { get; set; }
        public string Campo3 { get; set; }
        public string Cuadrante { get; set; }
        public string Spool { get; set; }
        public Nullable<int> EnHold { get; set; }
        public Nullable<int> Materiales { get; set; }
        public Nullable<int> Despachos { get; set; }
        public Nullable<int> Armado { get; set; }
        public Nullable<int> Soldadura { get; set; }
        public Nullable<int> Visual { get; set; }
        public Nullable<int> Dimensional { get; set; }
        public Nullable<int> DigRT { get; set; }
        public Nullable<int> PWHT { get; set; }
        public Nullable<int> Pintura { get; set; }
        public Nullable<int> PreparacionEmbarque { get; set; }
        public Nullable<int> PND { get; set; }
        public Nullable<int> PorcentajePND { get; set; }
        public Nullable<int> ProyectoID { get; set; }
        public Nullable<System.DateTime> FechaLocalizacion { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> DiametroMayor { get; set; }
        public string SistemaPintura { get; set; }
        public Nullable<int> StatusPND { get; set; }
        public Nullable<int> RequierePWHT { get; set; }
        public Nullable<int> HoldComentario { get; set; }
        public Nullable<int> NumeroJuntas { get; set; }
        public Nullable<int> SoloSoporte { get; set; }
    }
}
