//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subparte_Dragados
    {
        public string siglas { get; set; }
        public string descripcion { get; set; }
        public int secuencia { get; set; }
        public string ProyectoID { get; set; }
    }
}
