//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTransferenciaSpoolModificado
    {
        public int TransferenciaSpoolID { get; set; }
        public int SpoolID { get; set; }
        public bool SpoolPreparado { get; set; }
        public System.DateTime FechaPreparacion { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
        public bool Cancelado { get; set; }
        public Nullable<int> TransferenciaID { get; set; }
        public bool CanceladoTransferencia { get; set; }
    }
}
