//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoFabClass
    {
        public int FamiliaAceroID { get; set; }
        public decimal MXDiaMax { get; set; }
        public decimal MXDiaMin { get; set; }
        public decimal JuntaDiaMax { get; set; }
        public decimal JuntaDiaMin { get; set; }
        public decimal EspesorMax { get; set; }
        public decimal EspesorMin { get; set; }
        public string FabClas { get; set; }
        public int TipoJuntaID { get; set; }
        public int Prioridad { get; set; }
    }
}
