//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoJunta
    {
        public TipoJunta()
        {
            this.AgrupadoresSpoolPND = new HashSet<AgrupadoresSpoolPND>();
            this.CostoArmado = new HashSet<CostoArmado>();
            this.CostoProcesoRaiz = new HashSet<CostoProcesoRaiz>();
            this.CostoProcesoRelleno = new HashSet<CostoProcesoRelleno>();
            this.JuntaSpool = new HashSet<JuntaSpool>();
            this.JuntaSpoolPendiente = new HashSet<JuntaSpoolPendiente>();
            this.Peq = new HashSet<Peq>();
        }
    
        public int TipoJuntaID { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public bool VerificadoPorCalidad { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
        public bool PermiteTerminadoRelleno { get; set; }
    
        public virtual ICollection<AgrupadoresSpoolPND> AgrupadoresSpoolPND { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<CostoArmado> CostoArmado { get; set; }
        public virtual ICollection<CostoProcesoRaiz> CostoProcesoRaiz { get; set; }
        public virtual ICollection<CostoProcesoRelleno> CostoProcesoRelleno { get; set; }
        public virtual ICollection<JuntaSpool> JuntaSpool { get; set; }
        public virtual ICollection<JuntaSpoolPendiente> JuntaSpoolPendiente { get; set; }
        public virtual ICollection<Peq> Peq { get; set; }
    }
}
