//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCorte
    {
        public TipoCorte()
        {
            this.CorteSpool = new HashSet<CorteSpool>();
            this.CorteSpool1 = new HashSet<CorteSpool>();
            this.CorteSpoolPendiente = new HashSet<CorteSpoolPendiente>();
            this.CorteSpoolPendiente1 = new HashSet<CorteSpoolPendiente>();
            this.NumeroUnico = new HashSet<NumeroUnico>();
            this.NumeroUnico1 = new HashSet<NumeroUnico>();
        }
    
        public int TipoCorteID { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool VerificadoPorCalidad { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<CorteSpool> CorteSpool { get; set; }
        public virtual ICollection<CorteSpool> CorteSpool1 { get; set; }
        public virtual ICollection<CorteSpoolPendiente> CorteSpoolPendiente { get; set; }
        public virtual ICollection<CorteSpoolPendiente> CorteSpoolPendiente1 { get; set; }
        public virtual ICollection<NumeroUnico> NumeroUnico { get; set; }
        public virtual ICollection<NumeroUnico> NumeroUnico1 { get; set; }
    }
}
