//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportista
    {
        public Transportista()
        {
            this.Recepcion = new HashSet<Recepcion>();
            this.TransportistaProyecto = new HashSet<TransportistaProyecto>();
        }
    
        public int TransportistaID { get; set; }
        public int ContactoID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Contacto Contacto { get; set; }
        public virtual ICollection<Recepcion> Recepcion { get; set; }
        public virtual ICollection<TransportistaProyecto> TransportistaProyecto { get; set; }
    }
}
