//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencia
    {
        public Transferencia()
        {
            this.TransferenciaSpool = new HashSet<TransferenciaSpool>();
        }
    
        public int TransferenciaID { get; set; }
        public string NumeroTransferencia { get; set; }
        public System.DateTime FechaTransferencia { get; set; }
        public Nullable<int> DestinoID { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual Destino Destino { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<TransferenciaSpool> TransferenciaSpool { get; set; }
    }
}
