//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tubero
    {
        public Tubero()
        {
            this.DestajoTubero = new HashSet<DestajoTubero>();
            this.JuntaArmado = new HashSet<JuntaArmado>();
            this.JuntaCampoArmado = new HashSet<JuntaCampoArmado>();
        }
    
        public int TuberoID { get; set; }
        public int PatioID { get; set; }
        public string Codigo { get; set; }
        public string NumeroEmpleado { get; set; }
        public string Nombre { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
        public string AreaTrabajo { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<DestajoTubero> DestajoTubero { get; set; }
        public virtual ICollection<JuntaArmado> JuntaArmado { get; set; }
        public virtual ICollection<JuntaCampoArmado> JuntaCampoArmado { get; set; }
        public virtual Patio Patio { get; set; }
    }
}
