//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.BastonSpool = new HashSet<BastonSpool>();
            this.BastonSpoolJunta = new HashSet<BastonSpoolJunta>();
            this.CuadranteHistorico = new HashSet<CuadranteHistorico>();
            this.Destino = new HashSet<Destino>();
            this.Estacion = new HashSet<Estacion>();
            this.HistoricoWorkstatus = new HashSet<HistoricoWorkstatus>();
            this.Pendiente = new HashSet<Pendiente>();
            this.Pendiente1 = new HashSet<Pendiente>();
            this.PendienteDetalle = new HashSet<PendienteDetalle>();
            this.PersonalizacionSeguimientoJunta = new HashSet<PersonalizacionSeguimientoJunta>();
            this.PersonalizacionSeguimientoSpool = new HashSet<PersonalizacionSeguimientoSpool>();
            this.ProyectoCamposRecepcion = new HashSet<ProyectoCamposRecepcion>();
            this.ProyectoPendiente = new HashSet<ProyectoPendiente>();
            this.Transferencia = new HashSet<Transferencia>();
            this.TransferenciaSpool = new HashSet<TransferenciaSpool>();
            this.UsuarioProyecto = new HashSet<UsuarioProyecto>();
        }
    
        public System.Guid UserId { get; set; }
        public Nullable<int> PerfilID { get; set; }
        public string Nombre { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public string Idioma { get; set; }
        public bool BloqueadoPorAdministrador { get; set; }
        public bool EsAdministradorSistema { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
        public string VistaDashboard { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual aspnet_Users aspnet_Users1 { get; set; }
        public virtual ICollection<BastonSpool> BastonSpool { get; set; }
        public virtual ICollection<BastonSpoolJunta> BastonSpoolJunta { get; set; }
        public virtual ICollection<CuadranteHistorico> CuadranteHistorico { get; set; }
        public virtual ICollection<Destino> Destino { get; set; }
        public virtual ICollection<Estacion> Estacion { get; set; }
        public virtual ICollection<HistoricoWorkstatus> HistoricoWorkstatus { get; set; }
        public virtual ICollection<Pendiente> Pendiente { get; set; }
        public virtual ICollection<Pendiente> Pendiente1 { get; set; }
        public virtual ICollection<PendienteDetalle> PendienteDetalle { get; set; }
        public virtual Perfil Perfil { get; set; }
        public virtual ICollection<PersonalizacionSeguimientoJunta> PersonalizacionSeguimientoJunta { get; set; }
        public virtual ICollection<PersonalizacionSeguimientoSpool> PersonalizacionSeguimientoSpool { get; set; }
        public virtual ICollection<ProyectoCamposRecepcion> ProyectoCamposRecepcion { get; set; }
        public virtual ICollection<ProyectoPendiente> ProyectoPendiente { get; set; }
        public virtual ICollection<Transferencia> Transferencia { get; set; }
        public virtual ICollection<TransferenciaSpool> TransferenciaSpool { get; set; }
        public virtual ICollection<UsuarioProyecto> UsuarioProyecto { get; set; }
    }
}
