//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.Sam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wpq
    {
        public int WpqID { get; set; }
        public int WpsID { get; set; }
        public int SoldadorID { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaVigencia { get; set; }
        public Nullable<System.Guid> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte[] VersionRegistro { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Soldador Soldador { get; set; }
        public virtual Wps Wps { get; set; }
    }
}
